### ISSUE TITLE
Customiser Above Header Background Color Not Working With Transparent Header.

### ISSUE THREAD

**Issue by Chudz** [brainstormforce/astra#1050]
If I have a transparent header and an above header section enable. The above header section does not honour its own setting in the Colors & Backgrounds customiser section and will use the background from the Transparent Header. This only happens on desktop view.

**Comment by shubhw12** [comment]
@Chudz This is intended and expected behavior when you enable transparent header it is enabled for above as well as below header. In case you require separate color for the above header with a transparent header we can manage it with some custom CSS.
