### ISSUE TITLE
Logos do not display properly in AMP

### ISSUE THREAD

**Issue by westonruter** [brainstormforce/astra#1067]
I've selected the Logo, Retina Logo, and Mobile Logo as follows:

![image](https://user-images.githubusercontent.com/134745/53989476-ecb76180-40da-11e9-93fd-62d5854ab061.png)

# Non-AMP

For mobile it appears as:

![image](https://user-images.githubusercontent.com/134745/53989559-1a9ca600-40db-11e9-9fd3-49890b49614b.png)

For desktop it appears as:

![image](https://user-images.githubusercontent.com/134745/53989538-0d7fb700-40db-11e9-8c63-a42e2c8cb856.png)

# AMP

🐛  In mobile, the both the retina and mobile logos are appearing:

![image](https://user-images.githubusercontent.com/134745/53989603-2d16df80-40db-11e9-9171-8c3f8a5ba32d.png)

🐛  In desktop, I see something similar:

![image](https://user-images.githubusercontent.com/134745/53989821-b8907080-40db-11e9-9b40-784c9ddd1319.png)

**Comment by westonruter** [comment]
One solution could be to hide the container link elements, rather than contained image elemts themselves.

**Comment by Nikschavan** [comment]
Thank you for reporting this 👍

The CSS from the non-AMP layout still works here, although there was another CSS which had higher weight and was force-displaying the logo.

PR #1078 will fix this.

**Comment by Nikschavan** [comment]
Actually, hiding the container link instead of images also helps accessibility by removing the link of the logo from tab navigation in the desktop where it should not be present. Changed the PR accordingly.

**Comment by Nikschavan** [comment]
Closing this as this was fixed with #1078 and the latest update to the theme v1.7.2

**Comment by westonruter** [comment]
Added Astra to https://amp-wp.org/showcases/

**Comment by Nikschavan** [comment]
That's great @westonruter! Thank you very much :)

We are working on getting our plugin [Ultimate Addons for Gutenberg](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/) compatible with Native AMP. That way we can make ready-to import, AMP ready sites from [Astra Starter Sites](https://wpastra.com/ready-websites/?page-builder=gutenberg&category=all)
