### ISSUE TITLE
Footer widgets not properly displayed anymore

### ISSUE THREAD

**Issue by neat-web** [brainstormforce/astra#1068]
I am currently using WordPress 5.1 and PHP 7.1.26. After the Astra 1.7.0 update I noticed that the footer widgets are not properly displayed anymore. A character ">" appears in front of them and looking at the sourcecode it seems like some flawed PHP. I reproduced the exact same behaviour on a new WordPress installation.

`<div class="ast-footer-widget-1-area" <?php="" echo="" apply_filters(="" "astra_sidebar_data_attrs",="" "",="" $widget_id="" );="" ?="">&gt;<aside id= [...]`

<img width="93" alt="error" src="https://user-images.githubusercontent.com/36847572/53990776-53636c00-4129-11e9-8cf3-08d7a393bdc1.PNG">

**Comment by Nikschavan** [comment]
Thank you for reporting this @neat-web. This is fixed here on GitHub and we will push out a bugfix update very soon.
