### ISSUE TITLE
1.7.1 Custom Layouts

### ISSUE THREAD

**Issue by medvedbne** [brainstormforce/astra#1077]
Trying to use Hook for custom layouts to insert, however after publishing, clicking on the edit with elementor does nothing. 
Also all my hook settings are re-set and i'm left with only this: 
![Screenshot_18](https://user-images.githubusercontent.com/34314619/54094627-99773480-43a2-11e9-85b5-19cdbdcc2a45.jpg)

**Comment by Nikschavan** [comment]
The values are being saved although it is not displaying correctly in the admin area.
We will be sending an update ASAP for Astra Pro for this fix.
