### ISSUE TITLE
Order button text is transparent and not visible

### ISSUE THREAD

**Issue by ivan-borisov** [brainstormforce/astra#1179]
Order button text is transparent
![Screenshot_2019-05-27 Начало - торти Елиза ](https://user-images.githubusercontent.com/5180111/58394233-e508b880-804a-11e9-9471-ad06cc75a02a.png)
![Screenshot_2019-05-27 Начало - торти Елиза (1)](https://user-images.githubusercontent.com/5180111/58394237-e89c3f80-804a-11e9-8975-6d6b7eef0e47.png)

On firebug, I see this
```
.ast-site-header-cart .widget_shopping_cart .buttons .button.checkout, .woocommerce .widget_shopping_cart .woocommerce-mini-cart__buttons .checkout.wc-forward {

    color: transparent;

}
```

**Comment by thebengalboy** [comment]
The problem has already been resolved, but for some reason, the GitHub issue remained open. We will now close it.

If you encounter a similar issue, please don't hesitate to open a new one.
