### ISSUE TITLE
Missing translation string

### ISSUE THREAD

**Issue by ivan-borisov** [brainstormforce/astra#1184]
Some strings are missing on source pot file, other are available but after translation continue to display source language.

![screenshot-ivanborisov com-2019 05 28-12-00-56](https://user-images.githubusercontent.com/5180111/58469116-8a08bb80-8147-11e9-9756-a17386d563ca.png)
![screenshot-ivanborisov com-2019 05 28-12-18-36](https://user-images.githubusercontent.com/5180111/58469117-8a08bb80-8147-11e9-9a9f-187e08f1ead0.png)
![screenshot-ivanborisov com-2019 05 28-12-26-10](https://user-images.githubusercontent.com/5180111/58469119-8aa15200-8147-11e9-8658-271559191a51.png)
![screenshot-ivanborisov com-2019 05 28-12-29-07](https://user-images.githubusercontent.com/5180111/58469120-8aa15200-8147-11e9-9011-ccc59c15902c.png)
![screenshot-ivanborisov com-2019 05 28-12-38-29](https://user-images.githubusercontent.com/5180111/58469121-8aa15200-8147-11e9-93a1-91eea05c0250.png)

**Comment by premanshup** [comment]
@ivan-borisov 

**1. We have added translations for the below Strings in the version 2.0.0** #1392 

![meta-translation](https://user-images.githubusercontent.com/36841355/63212591-9851ec80-c124-11e9-99b5-219d1dfac198.png)

![footer-widgets-translation](https://user-images.githubusercontent.com/36841355/63212602-b586bb00-c124-11e9-87f9-a676dddc60f1.png)

**2. For Disable text we have replaced it with the new image which does not have any text so this is skipped from translation.**

**_Earlier it was this:_**

![58469120-8aa15200-8147-11e9-9011-ccc59c15902c](https://user-images.githubusercontent.com/36841355/63212628-1c0bd900-c125-11e9-9315-c0b04c31ef73.png)

**_Now the Disable image looks like this:_**

![60f09d663a7458008ba12ffda1eea641 _Image 2019-08-17 at 7 28 40 PM](https://user-images.githubusercontent.com/36841355/63212702-21b5ee80-c126-11e9-81a3-d2359b055393.png)

**3. Added Translation for the 'Customize Button Style.' string in the PR -** #1397

**4. Background translation string is added in the Astra Addon 2.0.0**

@ivan-borisov If you find any more untranslatable string s, please report them and we will add fix for them.
