### ISSUE TITLE
HOW TO CUSTOM STRING - PLEASE ADD A SNIPPE

### ISSUE THREAD

**Issue by angelitodiaz1** [brainstormforce/astra#1194]
Hi, I need to change de String when result not available on the site by search form.  By default, the estring is: "'string-search-nothing-found-message'    => __( 'Sorry, but nothing matched your search terms. Please try again with some different keywords.', 'astra' )" in class-theme-strings.php.

Do you have a way to change this text with a Snippe?   I looking for a Google about it and its failed.

Please help me.

Regards,

**Comment by premanshup** [comment]
@angelitodiaz1 Please use the below snippet to change the string of when nothing is found in the search result.

`add_filter( 'astra_default_strings', 'astra_change_string' );

/**
 * Function to change search nothing found string.
 *
 * @param array $defaults contains default string values.
 * @return array
 */
function astra_change_string( $defaults ) {
	$defaults['string-search-nothing-found-message'] = __( 'This is my custom Search Not Found String.', 'astra' );
	return $defaults;
}`
