### ISSUE TITLE
Theme check

### ISSUE THREAD

**Issue by szepeviktor** [brainstormforce/astra#1292]
Please consider using theme check and **benefit** from it.

- https://themecheck.info/
- https://wordpress.org/plugins/theme-check/

**Comment by premanshup** [comment]
@szepeviktor Thank you for suggesting the above checks. We will have our team look into this and will definitely make improvements accordingly.

**Comment by szepeviktor** [comment]
You could also use the tools of the WordPress Theme Review Team
https://github.com/WPTRT

**Comment by premanshup** [comment]
@szepeviktor We have tested the theme with your recommended tool and found to required changes though there were a couple of warnings/recommendations which can be ignored as they do not cause any issue in the code.

**Comment by szepeviktor** [comment]
@premanshup All right.

That is a business attitude.
If you plan to be error free in the long-term you may pick a tool and honor every warning it emits.

All the best!!

**Comment by Nikschavan** [comment]
We should try to remove all the warnings from the theme check. 
the best way is to add it along with the existing phpcs rulesets. but adding `WPThemeReview` ruleset overrides the Astra's [phpcs.xml.dist](https://github.com/brainstormforce/astra/blob/master/phpcs.xml.dist) and enables all the rules from `WPThemeReview`

I am re-opening this to add this later in the upcoming releases.

**Comment by szepeviktor** [comment]
Simply add the wptrt package, change WPCS version constrain, and adjust phpcs config

```diff
diff --git a/.gitignore b/.gitignore
index a6b94bab..2c64f3bf 100644
--- a/.gitignore
+++ b/.gitignore
@@ -29,3 +29,4 @@ astra

 # Ignore Composer's directories
 vendor/
+cghooks.lock
diff --git a/composer.json b/composer.json
index 5a1be4fd..cb4ece7e 100644
--- a/composer.json
+++ b/composer.json
@@ -1,9 +1,10 @@
 {
   "require-dev": {
         "dealerdirect/phpcodesniffer-composer-installer": "^0.4.4",
-        "wp-coding-standards/wpcs": "dev-master",
+        "wp-coding-standards/wpcs": "^2.1.0",
         "phpcompatibility/phpcompatibility-wp": "*",
-        "brainmaestro/composer-git-hooks": "^2.6"
+        "brainmaestro/composer-git-hooks": "^2.6",
+    "wptrt/wpthemereview": "^0.2.0"
     },
     "scripts": {
           "format": "phpcbf --standard=phpcs.xml.dist --report-summary --report-source",
@@ -19,4 +20,4 @@
                   ]
           }
   }
-}
\ No newline at end of file
+}
diff --git a/phpcs.xml.dist b/phpcs.xml.dist
index 6f083a91..27173dae 100644
--- a/phpcs.xml.dist
+++ b/phpcs.xml.dist
@@ -1,15 +1,15 @@
 <?xml version="1.0"?>
 <ruleset name="WordPress Coding Standards for Plugins">
        <description>Generally-applicable sniffs for WordPress plugins</description>
-       <rule ref="PHPCompatibility">
+
+       <rule ref="WordPress-Core" />
+       <rule ref="WordPress-Docs" />
+       <rule ref="WPThemeReview">
                <exclude name="WordPress.PHP.StrictComparisons.LooseComparison" />
                <exclude name="WordPress.PHP.StrictInArray.MissingTrueStrict" />
        </rule>
        <config name="testVersion" value="5.3-"/>

-       <rule ref="WordPress-Core" />
-       <rule ref="WordPress-Docs" />
-
        <!-- Check all PHP files in directory tree by default. -->
        <arg name="extensions" value="php"/>
        <file>.</file>
```

Adn you need:
`sed -e '/name="testVersion"/d' -i vendor/wptrt/wpthemereview/WPThemeReview/ruleset.xml`

**Comment by szepeviktor** [comment]
The result is a list of 199 problems.
Please consider a PHP 5.3 compatible autoloader: Composer requires PHP 5.3.2+ to run, so simply including the autoloader part of composer in the distribution ZIP eliminates the need of all `require` in the code.

**Comment by Nikschavan** [comment]
I have added #1412 with updated phpcs rulesets.

We are currently not including WordPress-Extra ruleset in the phpcs check although most of the rules from this are included from `WPThemeReview`

**Comment by shubhw12** [comment]
We have fixed all of the warnings and errors of the theme check plugin in recent versions of Astra ( v2.5.5 ).

Here is a reference:  https://share.getcloudapp.com/E0urKlpE

**Comment by szepeviktor** [comment]
@shubhw12 Well done!

I hope you were not manufacturing a mountain of `/* ignore */` -s ⛰️
