### ISSUE TITLE
Delay in Navigation Menu appearance (not fixed in 1.8.7)

### ISSUE THREAD

**Issue by derweltbuerger** [brainstormforce/astra#1314]
Hi there,

I noticed sometime after one of the updates before 1.8.7 (I think it was with 1.8.5.) that the nav menu would only appear as the last thing on the page, which is unfortunate. I am pretty sure that before that the behaviour was different.

The nav menu does not have this sort of delay when I deactivate Astra Pro addon. However, I need it for sticky header and a few other things. Yesterday I saw that 1.8.7 was supposed to fix this because the changelog says: "Fix: Delay in Navigation Menu appearance." However, nothing changed for me after updating to 1.8.7 (both the theme and the plugin).

Using WP 5.2.1 with WooCommerce 3.6.4.

I tried deactivating all other plugins, which did not change anything about this behaviour. I also tried a menu with only one menu item, which did not change anything. The menu with only one item would still load very slow and as the very last thing on the page with Astra Pro activated. As soon as I deactivate Astra Pro, it loads much quicker and is visible from the very beginning.

Please have look into this and what might cause this behaviour because apparantly this bug has not completely been fixed with 1.8.7.

Thanks,
David

**Comment by Nikschavan** [comment]
Hello @derweltbuerger We have tested this to be working with a couple of sites, Can you try clearing any cache that you might have?

If you are still facing the same problem, can you open up a support ticket with your website URL?
