### ISSUE TITLE
Improve font rendering

### ISSUE THREAD

**Issue by mandava** [brainstormforce/astra#132]
Font smoothing helps to render fonts to be much smoother and thinner. This makes a lot of difference in readability perspective, especially when using Google Fonts. You can test these fonts to notice the difference: Source Sans Pro, Poppins etc.

html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

or 

body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

**Comment by Nikschavan** [comment]
Thank you very much for the suggestion @mandava,

We have updated the CSS to add this property - #134
