### ISSUE TITLE
Header menu stacking vertically on fresh install

### ISSUE THREAD

**Issue by avermat** [brainstormforce/astra#1474]
Recently, I've noticed that when I do a fresh install of WordPress + Astra, the main menu stacks on the right side of the header. In the past, it would be shown horizontally like normal. 

It's not until I create a menu in the admin (appearance > menu), that this goes away and it behaves normally. So if no menus have been created yet in the admin, the menu stacks like shown below:

![astra-header-no-menu](https://user-images.githubusercontent.com/29379115/66359903-700b9f00-e9ab-11e9-8b04-90e709fd0a25.png)

**Comment by shubhw12** [comment]
Hello @avermat. 

We were not able to find any such case on our end. 
Please see here:https://share.getcloudapp.com/8Lur9wdD

Also, we haven't received any query regarding the same before.

Feel free to start a new thread if you're still experiencing problems on your end
