### ISSUE TITLE
sub menu displays out of screen

### ISSUE THREAD

**Issue by discus2013** [brainstormforce/astra#1532]
As shown in the screen snapshot below:

![20191202-242112](https://user-images.githubusercontent.com/37330603/69926393-374bfa00-1504-11ea-94ea-826169b28326.jpg)

AstraVersion: 2.1.3

**Comment by UttamSharma007** [comment]
@discus2013 Please refer this article for the solution - 
https://wpastra.com/docs/change-the-direction-for-submenu-opening/

**Comment by shubhw12** [comment]
@discus2013 I hope the above solution works for you. I am closing this issue.
