### ISSUE TITLE
Please do not clear:both on headings

### ISSUE THREAD

**Issue by blogjunkie** [brainstormforce/astra#1627]
Astra's theme CSS applies clear:both to headings in `style.css` and `editor-style.css`

```css
h1, h2, h3, h4, h5, h6 {
  clear: both;
}
```

https://github.com/brainstormforce/astra/blob/ea3800f6455ac504b77b4cd60f5925626de563ba/assets/css/unminified/style.css#L1254

https://github.com/brainstormforce/astra/blob/ea3800f6455ac504b77b4cd60f5925626de563ba/assets/css/unminified/editor-style.css#L1253

This causes headings in the block editor to be cleared as well. In the example below, the image is floated left but because headings are cleared it starts on a new line:

![block_editor_headings](https://user-images.githubusercontent.com/1391919/75939971-bd425d00-5ec6-11ea-9a4c-6aa107e1edc2.png)

How it should work:

![correct_block_editor_headings](https://user-images.githubusercontent.com/1391919/75940045-eb27a180-5ec6-11ea-9e7c-8405be17fe01.png)

Thank you for making this small quality-of-life enhancement

**Comment by thebengalboy** [comment]
The issue should no longer exist with the most recent Astra version.
