### ISSUE TITLE
RTL problems with Astra theme

### ISSUE THREAD

**Issue by zrezaeimobin** [brainstormforce/astra#1683]
Hi,
Please include these 2 pieces of code into the them to solve 2 RTL problems.

This piece of CSS is for dropdown submenus on RTL sites:

@media (max-width: 768px){
.ast-header-break-point .main-header-bar .main-header-bar-navigation .menu-item-has-children>.ast-menu-toggle {
    left: calc(20px - .907em);
		right: unset;
}
}

This piece of code is for logo on Automattic AMP sites on RTL sites which should be on the right not left.

@media (max-width: 921px)
{.ast-amp .ast-mobile-header-inline .site-branding {
    text-align: right;
    padding-bottom: 0;
	}
}

BTW this is the site I'm using these pieces of code on: sanamedtour.com

**Comment by Nikschavan** [comment]
@premanshup Removing `needs-review` label as this is for PRs.

**Comment by SimranChougule1** [comment]
This issue is no longer present
