### ISSUE TITLE
Site Error 

### ISSUE THREAD

**Issue by thirupathimedi** [brainstormforce/astra#1740]
https://github.com/brainstormforce/astra/blob/e3377ef908f86a6fcdb74fbad44164fb51aeed3e/inc/core/theme-hooks.php#L485

**Comment by premanshup** [comment]
Hello @thirupathimedi , can you please explain the Site Error in more details? :-)

I tried adding the new function to this action from Child Theme and it seems to be working properly.

Please check the below screenshot.

[https://share.getcloudapp.com/rRu9KXx9](https://share.getcloudapp.com/rRu9KXx9)

**Comment by premanshup** [comment]
Closing this, due to lack of activity. Please reopen this, if you face this issue :-)
