### ISSUE TITLE
Break point text (768) appearing in #content::before

### ISSUE THREAD

**Issue by rhutch117** [brainstormforce/astra#1746]
For some reason the number 768 is added before the #content id. 

![Capture](https://user-images.githubusercontent.com/16389693/82695051-f36fbd00-9c29-11ea-89dc-e2e0cbfc3386.PNG)

The html and css are below

    
    <div id="content" class="site-content">
        ::before == $0
        ....

    #content::before {
        content: "768";
    }

This css is being loaded inline 

    <style id='astra-addon-css-inline-css'>
        #content:before{content:"768";}@media (max-width:768px)
        ...
    </style>

The @media query is also at 768 so I'm thinking that somewhere that number is inadvertently being written to the content attribute. 

I've briefly searched the inc/class-astra-dynamic-css.php file but didn't see the cause.

**Comment by imnavanath** [comment]
Hi @rhutch117,
Can you please open a support ticket from [here](https://wpastra.com/support/free-support/). So we can take a closer look at it and provide you a dev version with the fix.

**Comment by gravnetic** [comment]
![before-css-hardcoded-content](https://user-images.githubusercontent.com/475331/83532501-8f5fbb00-a4ab-11ea-91d4-a6d67bf4264f.jpg)

**Comment by premanshup** [comment]
@rhutch117 Thank you for reporting this issue, we have released a fix for this issue in the Astra Pro [version 2.5.1](https://wpastra.com/changelog/astra-pro-addon/). I'd suggest you to please update the Astra Pro to version 2.5.1.

**NOTE:** After updating it. disable and then enable **Blog Pro** addon from the **Astra Settings** page, and clear all cache ( including server or cdn ). Then check your website, this issue should then get fixed.
