### ISSUE TITLE
Astra mega menu (html widget) not translatable

### ISSUE THREAD

**Issue by venigo** [brainstormforce/astra#1838]
There Is no possibility to translate / sync the mega menu (html widget) to English in combination with wpml. The html widget / custom mega menu possibility is completely missing.
--
![IMG_20200809_174212](https://user-images.githubusercontent.com/12639201/89736155-af8d9680-da67-11ea-86dc-40fed4b207d7.jpg)

**Comment by thebengalboy** [comment]
This should be solved with Astra version 4.0.0 which came with a new mega menu. If not, please let us know.
