### ISSUE TITLE
Post Title Almost Invisible in Gutenberg Editor

### ISSUE THREAD

**Issue by realstephenzhao** [brainstormforce/astra#1847]
### Describe the bug:
My post title(default post type) is almost invisible in Gutenberg Editor due to settings in `inc/assets/js/block-editor-script.js`.
I found some setting in it started from line 45:
```
var title_checkbox = document.getElementById('site-post-title');
var title_block = document.querySelector('.editor-post-title__block');

title_checkbox.addEventListener('change',function() {
            
    if( title_checkbox.checked ){	

        title_block.style.opacity = '0.2';
    }
    else {
        title_block.style.opacity = '1.0';
    }
});
```

### To reproduce:
1. Use lastest Astra theme
2. Created a post, input some words in post title area

### Expected behavior:
The post title block shouldn't be set to `opacity: 0.2;`

### Screenshots:
![Wrong opacity in post title](https://i.imgur.com/SrA4wIr.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Lastest version

### Astra Theme version:
I can't remember when it occured and since which version, about 3-5 months ago.

**Comment by shubhw12** [comment]
@realstephenzhao 
This doesn't seem to be an issue,
Let me explain the scenario. 
We have intentionally added such a feature in one of our recent updates of Astra (v2.4.4).
This was introduced so as to avoid confusion to the user. 
Astra provided an option to enable and disable the title, You can enable/disable title for all of your from the customizer or you can disable for particular page post from the page meta settings as well.
Please refer here: 
Option in the customizer ( https://share.getcloudapp.com/9ZuXdG4m )
Option in meta setting for a particular page ( https://share.getcloudapp.com/WnuJxKd0 )
So if you disable the title on your site or for a particular page/post, you will see that the title in the Gutenberg editor will have a low opacity which indicates that the title is currently disabled for the page/post.

**Comment by realstephenzhao** [comment]
> Option in meta setting for a particular page ( https://share.getcloudapp.com/WnuJxKd0 )

I didn't check this "Disable Title" option in Post admin edit page.

> Option in the customizer ( https://share.getcloudapp.com/9ZuXdG4m )

Actually options in Customizer like "Featured Image" "Title & Blog Meta" are all turned off, because I don't use Astra single post layout, I use Elementor page builder template.

So how can I restore the original css opacity in this situation?

**Comment by shubhw12** [comment]
@realstephenzhao, In this case, we are trying to override the functionality that is provided by the theme. So we can manage this with the help of child theme and custom CSS. You can paste the following code in the functions.php file of your child theme.
```
add_action('admin_head', 'astra_title_opacity');
function astra_title_opacity(){
	?>
	<style>
	.edit-post-visual-editor__post-title-wrapper .editor-post-title__block{
		opacity: 1;
	}
	</style>
	<?php
}
```
If you need any help with how to custom code in the child theme please refer the following doc
https://wpastra.com/docs/add-custom-php-code/#3.-in-child-theme

**Comment by realstephenzhao** [comment]
> 
> 
> @realstephenzhao, In this case, we are trying to override the functionality that is provided by the theme. So we can manage this with the help of child theme and custom CSS. You can paste the following code in the functions.php file of your child theme.
> 
> ```
> add_action('admin_head', 'astra_title_opacity');
> function astra_title_opacity(){
> 	?>
> 	<style>
> 	.edit-post-visual-editor__post-title-wrapper .editor-post-title__block{
> 		opacity: 1;
> 	}
> 	</style>
> 	<?php
> }
> ```
> 
> If you need any help with how to custom code in the child theme please refer the following doc
> https://wpastra.com/docs/add-custom-php-code/#3.-in-child-theme

Thanks for your help. Hope there would be an option built in Astra theme to solve this problem.

**Comment by shubhw12** [comment]
@realstephenzhao 

I am glad that I was able to help.

This feature was introduced to avoid confusion for the user. We haven't received any other queries from the users regarding the same. 

If we have a considerable amount of users facing any difficulties with this feature, we would definitely work on it and see how we can improve this in our future updates.

Thank you ;)
