### ISSUE TITLE
Customize headings not working well with Gutenberg plugin

### ISSUE THREAD

**Issue by jaguarondi** [brainstormforce/astra#1936]
### Describe the bug:
The appearance->customize->global->typography->Headings are not displayed correctly if the Gutenberg plugin is installed separately.

### To reproduce:
Fresh wordpress and astra theme install, theme Headings settings are displayed correctly. If I install and activate the Gutenberg plugin 9.0.0, the settings on the left are not displayed correctly, see screenshot.

### Screenshots:
Without the plugin:
<img width="319" alt="Screenshot 2020-09-24 at 05 21 49" src="https://user-images.githubusercontent.com/5890314/94097418-c2e19f00-fe26-11ea-9eea-f46657a080d4.png">

After the plugin install:
<img width="317" alt="Screenshot 2020-09-24 at 05 20 51" src="https://user-images.githubusercontent.com/5890314/94097452-cf65f780-fe26-11ea-98b4-affc615cc0ca.png">

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:

Wordpress 5.5.1

### Astra Theme version:

Astra 2.5.5

**Comment by shubhw12** [comment]
@jaguarondi 

We had the scenario with the Gutenberg plugin ( from v8.9.0 to v9.1.0 ). The issue was fixed in one of the recent versions of the Gutenberg plugin ( v9.1.0 ).

I hope this helps.

Thank you.
