### ISSUE TITLE
global colors syncing

### ISSUE THREAD

**Issue by codeagencybe** [brainstormforce/astra#2007]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
It would be nice if AstraWP can also sync the colors from customizer with the new Elementor global colors feature, just like KadenceWP theme has. 
This is such a timesaver. 

### Describe alternatives you've considered
Using Central Color Palette for some time now, but after the Global Color feature in Elementor, this is no longer working. 
The color picker does no longer show the colors from this plugin. 
In the past I always enjoyed this plugin to set my colors 1 time and use them both in Elementor and AstraWP customizer settings. 
Now they are no longer "synced" together. 
LINK: https://nl.wordpress.org/plugins/kt-tinymce-color-grid/

### Additional context/screenshots/videos
https://www.youtube.com/watch?v=51fWd8w9RwA

**Comment by shubhw12** [comment]
@codeagencybe 

Thanks for the suggestion.

This is currently on our road map and you will find this in our theme soon.

We really appreciate your concern for our products.

Have a great day!

**Comment by codeagencybe** [comment]
@shubhw12 
Nice to hear!!
Any ETA when we can expect this release? because "soon" can mean anything between a few days and even a year sometimes. 

Thanks!

**Comment by shubhw12** [comment]
@codeagencybe 
I don’t have an ETA from the team behind it yet, but from their last update, I’d say we’re close to releasing it in one of our upcoming updates.
