### ISSUE TITLE
REM units for fonts

### ISSUE THREAD

**Issue by codeagencybe** [brainstormforce/astra#2008]
### Is your feature request related to a problem? Please describe.
Yes, I don't see how to set REM units for fonts. I only have px and em available.

### Describe the solution you'd like
add REM also as so many other themes have it too.

### Describe alternatives you've considered
better responsive fonts instead of hand picking and setting it

**Comment by shubhw12** [comment]
Hello @codeagencybe,

Thank you for the suggestion,

I have added this to our internal board as a feature request, we will check on this in the future and see how we can improve it in our upcoming updates.

Thank you!
