### ISSUE TITLE
Astra Pro Feature Request | Display Logic

### ISSUE THREAD

**Issue by perks98** [brainstormforce/astra#2010]
### Is your feature request related to a problem? Please describe.
More display logic similar to Elementor

### Describe the solution you'd like
Add display rules and exclusions for parent and child pages

### Describe alternatives you've considered
Using Elementor's own where possible but that is restricting and what you can achieve while with Astra there are more areas to dynamically display.

**Comment by shubhw12** [comment]
Hello @perks98,

Thank you for the suggestion,

I have added this to our internal board as a feature request, we will check on this in the future and see how we can improve it in our upcoming updates.

Thank you!
