### ISSUE TITLE
Astra Theme Visited Pseudo BUG

### ISSUE THREAD

**Issue by perks98** [brainstormforce/astra#2011]
### Describe the bug:
When you hover over a theme button it should use the hover pseudo but when it is a previously visited link it uses the visited pseudo which you cannot edit in the theme customiser. The only way to get around it is to use Elementor's theme customizer which defeats the purpose of the Astra theme in that regard. 

### Expected behavior + Suggested solution:
Remove the visited pseudo from your theme css or add the option to customise it.

### To reproduce + Video:
Old video on a previous Astra update that I sent via email to your support email with no update but the problem still persists on the latest version.
[https://share.getcloudapp.com/jkuD1EPN](https://share.getcloudapp.com/jkuD1EPN)

An example of one of my sites that has this issue with the latest updates is this page (https://www.wildflowers-online.co.uk/about/) before the footer if you click on that contact us button then navigate back to that page then you now hover over it will be pure black.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

**Comment by thebengalboy** [comment]
We have confirmed that the issue you reported is not reproducible with the latest version of Astra. If the problem persists, please let us know and we will investigate further.
