### ISSUE TITLE
Add AMP meta so Astra theme can be used as reader theme.

### ISSUE THREAD

**Issue by milindmore22** [brainstormforce/astra#2019]
### Is your feature request related to a problem? Please describe.
This feature will add the capability to use Astra as a reader theme in the official [AMP](https://wordpress.org/plugins/amp/) plugin 

### Describe the solution you'd like
The simple solution is to add `AMP:true` meta in themes style.css this will mark the theme to be available as a reader theme.

reference: https://amp-wp.org/documentation/playbooks/adding-reader-themes/

### Additional context/screenshots/videos
Final Outcome : 

![image](https://user-images.githubusercontent.com/1132541/100265271-05823d80-2f76-11eb-8019-6b0e804ec56f.png)

**Comment by premanshup** [comment]
@milindmore22 Thank you for the PR #2020, it is merged in the `next-release` and should be released in the `v3.2.0`. Closing this issue.
