### ISSUE TITLE
Add mobile screenshot for astra theme.

### ISSUE THREAD

**Issue by milindmore22** [brainstormforce/astra#2021]
### Is your feature request related to a problem? Please describe.
It's recommended to have `screenshot-mobile` image file it's used by most modern day plugins.

### Describe the solution you'd like
Add image file in themes root as  `screenshot-mobile.jpg`

### Additional context/screenshots/videos

AMP plugin was not able to find mobile screenshot so it falls back with the desktop screenshot you can check `neve` has added it 

![image](https://user-images.githubusercontent.com/1132541/100266390-bfc67480-2f77-11eb-9bed-97621e09277b.png)

**Comment by premanshup** [comment]
Thank you for the PR @milindmore22 ❤️
