### ISSUE TITLE
Improvements Notes for Astra v3

### ISSUE THREAD

**Issue by perks98** [brainstormforce/astra#2056]
Just tried the new Astra v3 header and footer builder. The HTML and Copyright widgets use the WYSIWYG text editor. The text is automatically centre aligned in footer so when you left or right align it adds <p> around it. I'd prefer the standard <span>. Please look into this before release.

**Comment by shubhw12** [comment]
Hello @perks98 

Thank you for getting in touch regarding this.

This is to let you that we are closing this issue as of now, I have added a task for this in our internal project board and we will be tracking those tasks internally and see how we can implement them in our future versions.

The discussions regarding this can be still continued in the thread here.

We really appreciate your concern for our product.

Have a great day ahead!
