### ISSUE TITLE
alignwide class now working as expected with Gutenberg

### ISSUE THREAD

**Issue by danielcharrua** [brainstormforce/astra#2223]
### Describe the bug:
Rendering a block using .alingwide cuts sides when page resize if page is smaller than the default width. The breakpoint is set the same as the header breakpoint. This is a clear BUG to me.

### To reproduce:
1. Add page and Media & Text Block on WP fresh installation with Astra theme
2. Apply alignwide option from block options
3. Save and see page preview or render it on frontend
4. See margin errors not working as expected, the information on sides gets cut on resize.

### Expected behavior:
When resizing the page and using alignwide, the theme should be responsive and have no cutting on side edges.

### Screenshots:
Video:
https://youtu.be/xgp2LnfSwP0

Expected:
https://prnt.sc/wl4bwd

Error:
https://prnt.sc/wl4cqc

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.6

### Astra Theme version:
2.6.2

**Comment by thebengalboy** [comment]
The issue no more exists with the newer versions.
