### ISSUE TITLE
Learndash "View Older" not working since Astra 3

### ISSUE THREAD

**Issue by Seb-Fe** [brainstormforce/astra#2246]
When a Learndash lesson has more than 20 topics, the older ones go to a "next page" that is loaded inside the same page
![older](https://user-images.githubusercontent.com/33849340/105037530-df8c8d00-5a3c-11eb-9e49-67c3514e2baa.png)

Since updating to Astra 3, this is not working. Everytime the user clicks to see the next page, it keeps loading forever, so making the older topics impossible to see.

Astra Theme and Learndash are updated, but I'm not updating Wordpress to 5.6 because of conflict to other plugins.

**Comment by premanshup** [comment]
@Swapnildhanrale Sir, please get this tested.

**Comment by premanshup** [comment]
@Seb-Fe We checked this on our testing website and it seems to be working properly with the Astra 3.0.0 version.

Please check the screencast here - [https://a.cl.ly/7KubDZR2](https://a.cl.ly/7KubDZR2) 

Here is what you can do to debug this:
﻿
1. Please try switching to another theme, like [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/), and check whether the issue persists. If yes, then it is not the theme that is causing the error.
﻿
2. Deactivate all plugins temporarily and see if that solves the problem. Then, activate plugins one by one to see which plugin is causing the problem.
﻿
This is a general debugging process that all WordPress support teams perform to find 90% of the problems. [Here is a video that explains the process](https://www.youtube.com/watch?v=yWEnKnzwc0U). If you're concerned the debugging process might break your website, you can take a quick backup of your website as [explained in this video](https://www.youtube.com/watch?v=jXb512M_WSY&feature=youtu.be&t=120).

Let us know if you find anything after the debugging process.

**Comment by Seb-Fe** [comment]
Thanks for the response. You are right, the problem has nothing to do with Astra. It was just a coincidence that it happened the same day I updated.

**Comment by shubhw12** [comment]
@Seb-Fe Thanks for letting us know. I am closing this issue now.
