### ISSUE TITLE
Mobile menu not working in AMP pages

### ISSUE THREAD

**Issue by SEOsakht** [brainstormforce/astra#2269]
### Describe the bug:
Mobile menu not working in AMP pages ... When clicking on toggle icon nothing happen.

### To reproduce:
1. Install and activate AMP plugin
2. Go to an AMP page in mobile mode
3. Click on toggle menu

### WordPress version:
WordPress 5.6 

### Astra Theme version:
Astra 3.0.1

**Comment by SEOsakht** [comment]
Same problem in Astra 3.0.2

**Comment by SEOsakht** [comment]
Same problem in Astra 3.0.3

**Comment by CezaryStrus** [comment]
Any reply? We still have a problem astra 3.1.0

**Comment by rohitp-bsf** [comment]
Hello @SEOsakht ,

Sorry for the delayed reply & Thank you for reporting this issue.

We have already added this issue to our development queue and will be fixing this on priority.

**Comment by vrundakansara** [comment]
Hello @SEOsakht , I have an update for you with this issue.
All the AMP issues will be fixed in v3.3.0 for Astra.
We appreciate all your patience.


_Regards,
Vrunda Kansara_

**Comment by SEOsakht** [comment]
Hi @rohitp-bsf & @vrundakansara ,
Thanks for your helps and response.

**Comment by CezaryStrus** [comment]
> Hello @SEOsakht , I have an update for you with this issue.
> All the AMP issues will be fixed in v3.3.0 for Astra.
> We appreciate all your patience.
> 
> _Regards, Vrunda Kansara_

so, when?

**Comment by SEOsakht** [comment]
> Hello @SEOsakht , I have an update for you with this issue.
> All the AMP issues will be fixed in v3.3.0 for Astra.
> We appreciate all your patience.
> 
> _Regards, Vrunda Kansara_

Seems the problem persists in v3.3.0 of Astra ...

**Comment by SEOsakht** [comment]
> Hello @SEOsakht , I have an update for you with this issue.
> All the AMP issues will be fixed in v3.3.0 for Astra.
> We appreciate all your patience.
> 
> _Regards, Vrunda Kansara_
Hello @vrundakansara ,
Seems the problem persists in v3.3.0 of Astra ...

**Comment by westonruter** [comment]
I've just updated to 3.3.2 and the mobile menu is still broken on AMP pages.

When in Transitional template mode, for example, compare:
 
## Non-AMP: Menu works

https://user-images.githubusercontent.com/134745/115593374-482c1580-a289-11eb-9e41-5d0e70d52efe.mov

## AMP: Menu does not work

https://user-images.githubusercontent.com/134745/115593403-4f532380-a289-11eb-958f-676470ff461b.mov

**Comment by Nikschavan** [comment]
The fix (#2548) for this issue is ready in the `next-release` branch and should be released in v3.4.0. This version is due to be released in a few days.

**Comment by chandan-reddy-k** [comment]
@Nikschavan I'm still facing this issue despite updating to v3.4.1.

When I use the old header & footer the `display` never changes from `none` to `block` 

![Screenshot 2021-05-02 at 7 19 16 PM](https://user-images.githubusercontent.com/43699825/116815636-12860700-ab7c-11eb-807a-9b5f950c888d.png)

Similarly when I try using the new header & footer builder, there are 2 places where `display` never changes to `block`

### in `main-header-bar-navigation` class

![Screenshot 2021-05-02 at 7 23 09 PM](https://user-images.githubusercontent.com/43699825/116815674-39dcd400-ab7c-11eb-9e6f-1bdb15987437.png)

---

### in `ast-mobile-header-content content-align-flex-start` class

![Screenshot 2021-05-02 at 7 23 25 PM](https://user-images.githubusercontent.com/43699825/116815676-3ba69780-ab7c-11eb-83a2-2e258b502913.png)

**Comment by Nikschavan** [comment]
@chandan-reddy-k - AFAIK the `AMP for WP` plugin provides it's own template files which override the templates (and css) from the theme. Can you [open a support ticket](https://wpastra.com/support/open-a-ticket/) and mention this issue so that I can check this for you.

This issue should be fixed for the official AMP plugin. The issue was we recently introduced a header builder and it's markup was not compatible with AMP since this was using JS to switch the header layouts in the frontend. We have updated this in v3.4.0 update which went live last week.

I will close this issue but feel free comment here if you think this is not fixed for your case.
