### ISSUE TITLE
Astra Sites Not Working

### ISSUE THREAD

**Issue by robneu** [brainstormforce/astra#237]
I couldn't find a repository for the Astra Sites plugin, so I'm opening this issue here. Right now, you have a JS error in `admin.js` which is rendering the plugin unusable.

On line 623 and line 646 you're missing references to `event` which is subsequently called within those functions. I haven't tested other browsers, but in Firefox this completely breaks the admin interface for browsing sites.

Adding a reference to the event fixes the issue. I would send a PR if I could. 🤔

**Comment by Nikschavan** [comment]
Hello @robneu,

Thank you for reporting the bug, I do confirm the bug on Firefox, This although does work nicely on Chrome and Safari.

The Astra Sites repo was private, We just got it public here - https://github.com/brainstormforce/astra-sites

We would love a PR :)

**Comment by robneu** [comment]
PR sent: https://github.com/brainstormforce/astra-sites/pull/1

✌️

**Comment by Nikschavan** [comment]
This was fixed as a part of https://github.com/brainstormforce/astra-sites/pull/4
This will be sent out in the today's update. 

Thank you for the effort @robneu, Feel free to PR for contributions anytime in the future :)
