### ISSUE TITLE
Pro: Advanced Headers Transparent Header mobile dropdown

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#239]
Hello! When we use Advanced Headers and Transparent Header the mobile dropdown is also transparent and it's ugly. Desktop dropdowns are also unmanageble. Add this option and you'll "kill two birds with one stone" — Desktop Dropdown = Mobile dropdown.

Thanks!

**Comment by Nikschavan** [comment]
That's a good suggestion @parfilo.
