### ISSUE TITLE
Pro: astra_head_bottom and wp_head what is the difference?

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#240]
Hello! Subject.
Both hooks doing the same thing — adds my snippet just before `<title>` tag.

Inspect and fix it please.

**Comment by parfilov** [comment]
The same situation with wp_footer and astra_body_bottom. I don't see a difference.

**Comment by Nikschavan** [comment]
Hello @parfilov,

`wp_head` and `wp_footer` are both WordPress's default hooks and many plugins hook their actions into these two actions.

The actions `astra_head_bottom ` and `astra_body_bottom` will ensure that the actions are executed on the correct priority.

Astra Pro uses these actions internally to add it's own code under a few settings.
