### ISSUE TITLE
Untranslatable strings report

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#242]
Hello! In translation process I've found untranslatable and mistaken strings. Here is the report.

Legend:
"#" - the way to the module
"—" - the string
********************************************

####Astra settings
###Addons
##Header Sections

— This module introduces two more header sections in the website header.

####Astra settings
###Addons
##Footer Widgets

— Add customizable widget areas above the main footer.

####Astra settings
###Addons
##License

— Not Active!
— Active!
— Your license is active.
— Enter your license key.. [placeholder]
— License successfully validated!

####Advanced Headers
###Display Rules
##Display On
#Specific Target

— Please enter 2 or more characters

— Search pages / post / categories

####Advanced Headers & Advanced Hooks
###Table with headers or hooks
##Display Rules [column]

— Display:

####Strings with mistake(s)
Targer header based on user role.

##`<artical>` mistake
astra_entry_bottom - Action to add your content or snippet at bottom of the `<artical>` tag.
astra_entry_after - Action to add your content or snippet after closing `<artical>` tag.

**Comment by parfilov** [comment]
####White Label
— Save Changes

**Comment by Nikschavan** [comment]
Thank you for reporting this @parfilov,

We have taken a note of these settings and will get these fixed in the next update.

**Comment by parfilov** [comment]
@Nikschavan another one In Customizer
####Layout
— Transparent Header

**Comment by Balachandark** [comment]
@parfilov  We have fixed all the untranslatable strings except for the license settings in our theme.
The license settings come from our Astra Addons Plugin. So the fixes for it will be done in Astra Add-ons Plugin in our future releases.
