### ISSUE TITLE
Transparent Header – Submenu background color not working.

### ISSUE THREAD

**Issue by TheB34n** [brainstormforce/astra#2462]
Even after updating my theme to 3.1.1 the submenu background color is not working. I have disabled/re-enabled both the theme and the transparent header.

**Comment by vrundakansara** [comment]
Hello @TheB34n , thank you for reporting this issue. We are in process of fixing the issue here - https://github.com/brainstormforce/astra/pull/2463
Very soon we will release an update regarding it.

_Regards,
Vrunda Kansara_

**Comment by shubhw12** [comment]
Hello @TheB34n, We have fixed this issue in Astra Theme v3.1.2. I am closing this issue thank you.
