### ISSUE TITLE
In header layout, fixed header, hide when scrolling down, does not work if jQuery Migrate is removed.

### ISSUE THREAD

**Issue by merquis** [brainstormforce/astra#2499]
In the menu, the fixed header option only works if we have jQuery Migrate enabled, do you plan to update the code to a recent version to be able to remove jQuery Migrate?

Best regards,

Jesus.

**Comment by vrundakansara** [comment]
@merquis - Thank you for reporting this to us.
I have added this to our task list.

**Comment by premanshup** [comment]
Task - https://wp-astra.atlassian.net/browse/AST-215
This will be released in the upcoming 2-3 versions.
@merquis closing this issue for now.

**Comment by drasier** [comment]
Hello, Thanks for taking this into account! Any updates? Still can't use fixed header when jquery-migrate is disabled. Wondering how things are going with this issue
