### ISSUE TITLE
Uncaught ReferenceError: astraNavMenuToggle is not defined

### ISSUE THREAD

**Issue by focusontec** [brainstormforce/astra#2527]
### Describe the bug:

Uncaught ReferenceError: astraNavMenuToggle is not defined

### Expected behavior:

After upgrade to Astra 3.2.0 (Pro version). Error occurs, Elementor page can not edited. 

### Screenshots:

![image](https://user-images.githubusercontent.com/31850584/112023999-b9838600-8b6e-11eb-955d-e9db11c0997b.png)
### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.6

**Comment by shubhw12** [comment]
Hello @focusontec 

I tried to reproduce the issue at our end but was not able to do so.

Could you please provide us some more information/ steps to reproduce the issue?

Looking forward to hearing back from you soon

**Comment by focusontec** [comment]
Thanks for reply. things become normal, maybe the cache problem. But I have another problem. and can not customize my theme after upgrade the Astra pro. And then I try to solve this by upgrade Astra theme. Nothing help.
![image](https://user-images.githubusercontent.com/31850584/113800237-2ca11500-9789-11eb-86a7-e5faa514d678.png)
See the latest issue I submit.

So disappointed, I swear I will never upgrade Astra. Never!
