### ISSUE TITLE
Astra Pro bug: Scroll To Top implementations could not work without jQuery dependency

### ISSUE THREAD

**Issue by evilaliv3** [brainstormforce/astra#2563]
The functionality Scroll to Top of astra pro is currently relying on jQuery and could not work without it

I consider it could be easily be reimplemented by means of a the standard JavaScript functions:

- getElementById/getElementByName/getElementByTag
- scrollIntoView

https://www.w3schools.com/jsref/met_element_scrollintoview.asp

**Comment by Nikschavan** [comment]
Thank you for this bug report @evilaliv3 - I have moved this to our internal backlog. We will try to fix this in the upcoming release cycles.

**Comment by evilaliv3** [comment]
Thank you @Nikschavan 

Actually the most simple and compatible code right now is the following:       ```document.getElementByTagName('body').scrollIntoView();```

I would just advise to use this.

**Comment by Nikschavan** [comment]
Agreed, We will although need to some polyfill for IE.
