### ISSUE TITLE
Widget 3 and 4 doesn't behave like Widget 1 and 2 in Footer Builder

### ISSUE THREAD

**Issue by maximebj** [brainstormforce/astra#2569]
### Describe the bug:
When trying to use the 4 widgets area in footer, an option panel pops with colors for widget 1 and 2, but not for 3 and 4. 
Also, there is no preview for theses widget when they are empty.

### To reproduce:

1. Go to Appearance > Customize > Footer Builder
2. Add Widget 1, 2, 3 and four wherever you want
3. click on Widget 1 and see the options panel on the left
4. click on Widget 3 and see the empty option panel (after a quick visual glitch 

### Expected behavior:
I except the same behavior for the 4 widgets area. But maybe there is a reason for this. 
In this configuration, I'm unable to change the text and link color of the widget, which is an issue with a dark background.

### Screenshots:
![widget-one](https://user-images.githubusercontent.com/1785489/113299140-d94c4400-92fc-11eb-805b-fecdd963752d.jpg)
![widget-2](https://user-images.githubusercontent.com/1785489/113299147-da7d7100-92fc-11eb-8da5-6ac64ec6f0a8.jpg)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7

### Astra Theme version:
3.2

**Comment by vrundakansara** [comment]
Hello @maximebj , this issue is already fixed in v3.3.0 which will come out next week.
Thank you for reporting the issue.

**Comment by maximebj** [comment]
And again, thanks a lot for the quick answer, and the quick fix !
