### ISSUE TITLE
Color Picker is sometime hidden due to an overflow: hidden

### ISSUE THREAD

**Issue by maximebj** [brainstormforce/astra#2570]
### Describe the bug:
Sometimes, the color picker doesn't have enough room to show entirely.

### To reproduce:
1. Go to Appearance > Customize > Footer Builder 
2. Click on design tab
3. Try to change the color of the background

### Expected behavior:
The color picker has enough room to be shown entirely, but it's hidden. 

It's because of an overflow: hidden in css in :
`#customize-theme-controls .customize-pane-child`

Solution : 
- remove overflow
- or force height of the pane at 100%

Another thing : 
I expected the same setting on the header builder (a background color for the whole header). But there isn't.

### Screenshots:
![Capture d’écran 2021-04-01 à 15 16 33](https://user-images.githubusercontent.com/1785489/113299603-58da1300-92fd-11eb-803b-e7e2ec0e760c.jpg)
![Capture d’écran 2021-04-01 à 15 16 42](https://user-images.githubusercontent.com/1785489/113299610-5aa3d680-92fd-11eb-9670-c7fa4f82083c.jpg)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7

### Astra Theme version:
3.2

**Comment by vrundakansara** [comment]
Hello @maximebj , this issue is already fixed in v3.3.0 which will come out next week.
Thank you for reporting the issue.

**Comment by maximebj** [comment]
Yes perfect ! 

Thanks for the great work. I appreciate it ! 💪
