### ISSUE TITLE
Can't remove border entirely, range field doesn't accept 0px

### ISSUE THREAD

**Issue by maximebj** [brainstormforce/astra#2571]
### Describe the bug:
Today, the only way to remove a border in Header or Footer builder, is to assign a transparent color to the border. It doesn't seems to be the most straightforward way to do it.

Plus, when trying to set the border size at 0px, the range field resets itself to 5px.

### To reproduce:
1. Go to Appearance > Customize > Header (or Footer) Builder 
2. click on the gear of any line
3. try to set the border size at 0px 

### Expected behavior:
Allow a size of 0px in the border size field
or 
add a switch button to enable / disable border

Maybe the pro version has more control about this. And I can totally understand that's it should be a paid feature. 
But at least allowing a 0px border would be nice. 

### Screenshots:
![border](https://user-images.githubusercontent.com/1785489/113301974-e4ed3a00-92ff-11eb-81bb-d7c95f126887.jpg)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7

### Astra Theme version:
3.2

**Comment by vrundakansara** [comment]
Hello @maximebj , thank you for reporting the issue.
We have used native WordPress RangeControl for the size option. This issue comes from native WordPress 5.7. We have reported this issue to the core team and we are looking forward to the fix in the upcoming update.

**Comment by maximebj** [comment]
Ok thanks, I just seen that it works well when you use the keyboard. In this way, we can get a 0px easily. 
Hope they fix it soon.
