### ISSUE TITLE
Mobile Menu doesn´t work correct after the last update.

### ISSUE THREAD

**Issue by JidWictut** [brainstormforce/astra#2622]
Hello,

after updating to the latest version of the theme and the pro version, the mobile menu does not work properly. I can no longer scroll down in the menu when the menu is longer than the screen.(on mobile Devices)
For example, when I open the first menu item "Rezepte" in my mobile menu, a submenu is displayed but I can't scroll down to the other menu items.

Best Regards

**Comment by premanshup** [comment]
@JidWictut Thank you for reporting this issue. It is fixed in #2622 and will be released in the v3.4.0 which is our upcoming release.
