### ISSUE TITLE
Astra Pro Russian translation is not updates

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#264]
Hello @Nikschavan and Brainstormforce team! I've translated Astra Pro at 100% but the translation not updates. Another themes and plugins translations works fine.

Thanks!

**Comment by Nikschavan** [comment]
Hello @parfilov,

We will be adding the translation files from the plugin in the next update. In future versions, we will try to automate this process so that the translations will also be shipped the same way as WordPress's translation updates are provided.

**Comment by parfilov** [comment]
@Nikschavan Oh, it would be nice to automate this process. I have this in Elementor Pro and my translations updates fast.
