### ISSUE TITLE
Existing comments not styled when post comments are disabled

### ISSUE THREAD

**Issue by someoddity** [brainstormforce/astra#2692]
Comments CSS is only loaded if comments are currently enabled on a post, however, sometimes posts previously had comments open and have existing comments even though they're closed now. In this case, comments still need display CSS.

This happens in the first conditional just inside both copies of `astra_comments_css()`.
https://github.com/brainstormforce/astra/blob/3282ea23bc1df3da42cad20091b7afd28d09a440/inc/dynamic-css/comments-flex.php#L25 https://github.com/brainstormforce/astra/blob/3282ea23bc1df3da42cad20091b7afd28d09a440/inc/dynamic-css/comments.php#L25

That function only checks if comments are currently open, not if there are any existing comments, but existing comments still need styling.

https://github.com/brainstormforce/astra/blob/3282ea23bc1df3da42cad20091b7afd28d09a440/inc/core/common-functions.php#L1524

It looks like `is_current_post_comment_enabled()` is also used in some conditionals for Customizer styling in inc/class-astra-dynamic-css.php (on lines [1703](https://github.com/brainstormforce/astra/blob/3282ea23bc1df3da42cad20091b7afd28d09a440/inc/class-astra-dynamic-css.php#L1703) and [1794](https://github.com/brainstormforce/astra/blob/3282ea23bc1df3da42cad20091b7afd28d09a440/inc/class-astra-dynamic-css.php#L1794)), so I'm not sure whether this fix belongs in the two conditionals above or in `is_current_post_comment_enabled()` itself, but checking whether there are existing comments for the post would resolve it:

`0 !== get_comments_post_number( get_the_ID() )`

**Comment by premanshup** [comment]
Thank you for reporting and sharing the details for this issue. This is fixed in this PR #2693 and will released soon.
