### ISSUE TITLE
Sub-menu width conflict in main.css and customizer settings

### ISSUE THREAD

**Issue by ceendicott** [brainstormforce/astra#2788]
### Describe the bug:
I should be able to define the width for the primary navigation sub-menu in header builder in customizer at a setting equal to the default sub-menu width as defined in assets > css > unminified > main.css (directly from the file):

.main-header-menu .sub-menu {
  width: 240px;
  background: #ffffff;
  left: -999em;
  position: absolute;
  top: 100%;
  z-index: 99999;
}

However, when I attempt to change the setting for the sub-menu width in customizer it does not allow me to set a width greater than 200px - even though the default setting is 240px. I'm not familiar with the code for the customizer on the back end so I'm not able to check and verify this on the backend.

I should be able to at least be able to return this setting back to its defined value of 240px. I would request that users should be able to set a width greater than 240px, but we can have that discussion another day as an enhancement request.

**PLEASE NOTE** I FULLY understand that the sub-menu width can simply be defined using css. However, what I'm trying to show is that there is a conflict between the width definition as defined in main.css and the range allowed in customizer. The customizer setting should be updated to a max of at least 240px.

### To reproduce:

Simply go into customizer > header builder > choose a primary navigation block > go to sub-menu settings > try to change/set a value greater than 240px.

### Expected behavior:

The maximum value should be 240px not 200px.

### Isolating the problem:

- [x] This bug happens with no other plugins activated - x
- [x] This bug happens with a default WordPress theme active - x
- [x] I can reproduce this bug consistently using the steps above - x

### WordPress version:
5.7.2

### Astra Theme version:
3.4.6

**Comment by ceendicott** [comment]
<img width="452" alt="Screen Shot 2021-05-24 at 10 56 14 AM" src="https://user-images.githubusercontent.com/84725053/119366175-ae3bfc00-bc7e-11eb-9c13-ef11ac7df2ed.png">
![Screen Shot 2021-05-24 at 10 56 55 AM](https://user-images.githubusercontent.com/84725053/119366247-c3188f80-bc7e-11eb-8d97-88332c7eb1a9.png)

**Comment by ceendicott** [comment]
![Screen Shot 2021-05-24 at 10 59 04 AM](https://user-images.githubusercontent.com/84725053/119366546-17237400-bc7f-11eb-8c01-6f33df904b95.png)

**Comment by premanshup** [comment]
@ceendicott Thank you for reporting this. We have added an improvement and changed the max value from 200 to 1920 in this PR #2799. 

So, now you should be able to set value up to 1920.

Screencast after the fix: [https://share.bsf.io/12u49gvv](https://share.bsf.io/12u49gvv)

Here is a development zip that you can download - [https://share.bsf.io/WnuxzyDG](https://share.bsf.io/WnuxzyDG)

This will be officially released in the `v2.5.0` of theme.
