### ISSUE TITLE
Typo in 404 page.

### ISSUE THREAD

**Issue by Ratko-Solaja** [brainstormforce/astra#281]
[In this file](https://github.com/brainstormforce/astra/blob/0dcc31f64ff413226ff0f21367208273d3cd00ea/inc/core/class-theme-strings.php) on line **34** there's a typo. Should be like this:

`'string-404-sub-title'                   => __( 'It looks like the link pointing here was faulty. Maybe try searching?', 'astra' ),`

**Comment by Nikschavan** [comment]
Thank you very much for reporting this @Ratko-Solaja :)

**Comment by rushijagani** [comment]
#286 404 page title typo is fixed.
