### ISSUE TITLE
Bug megamenu in hamburger mode

### ISSUE THREAD

**Issue by merquis** [brainstormforce/astra#2820]
### Describe the bug:
Error in megamenu. When opening a web page on the computer, if we shrink the window until the hamburger menu appears, when we click on any item, the submenu is not displayed. It is necessary to reload the page with F5 for the hamburger menu to display the submenus correctly. For the megamenu I use Elementor Pro and Shortcode in Menus https://es.wordpress.org/plugins/shortcode-in-menus/

### To reproduce:
1. Create a menu with Elementor PRO Section - Custom Grid.

2. Install Shortcode in Menus https://es.wordpress.org/plugins/shortcode-in-menus/

3. Add a shortcode submenu with the shortcode of the Elementor PRO template we created in step 1.

4. Open the website in full screen and set the window to small until the hamburger menu appears.

### WordPress version:
Wordpress 5.7.2

### Astra Theme version:
Astra 3.4.7
Astra Pro 3.4.2

**Comment by thebengalboy** [comment]
Astra version 4.0.0 is coming soon with revamped nav/mega menu. This will be solved with version 4.
