### ISSUE TITLE
Move H4 typography settings from Pro to Theme

### ISSUE THREAD

**Issue by ceendicott** [brainstormforce/astra#2823]
### Describe the solution you'd like
I should be able to set the typography settings for H4 headings in the theme typography customizer settings like you can for H1, H2, and H3. I fully realize that this was most likely deliberate to try and pump up the value of the paid/pro version, but I don't think being able to set the typography settings for H4 headings is driving sales of the pro version. Other "free" themes such as Kadence and Page Builder Framework have the H4 settings available in the free version. H5 and H6 could still be a pro feature.

The reason that I am requesting this change is to make it easier to utilize just the base theme for simple sites where the Pro plugin is not required as I'm trying to reduce the number of resources loaded to the minimum necessary and Pro currently adds at least one css file and one js file.

I've also thought about requesting an enhancement to combine the free version of the theme and pro version plugin so that you that you don't have a theme css/js files and a plugin css/js files, but I'll save that for another day :-).

### Describe alternatives you've considered
I understand and know that h4 can be modified by css and that's certainly a workable alternative but I think that there is sufficient value to having all heading settings in one place. I also don't load my child theme's css file as I usually have no need (which also speaks to the strength of Astra).

### Additional context/screenshots/videos

Astra Settings:

<img width="380" alt="Screen Shot 2021-06-01 at 2 33 28 PM" src="https://user-images.githubusercontent.com/84725053/120373429-58063300-c2e6-11eb-8dc4-d480b2beb14f.png">

Kadence Settings:
<img width="400" alt="Screen Shot 2021-06-01 at 2 34 21 PM" src="https://user-images.githubusercontent.com/84725053/120373537-7704c500-c2e6-11eb-8291-02e22b16e9f8.png">

Page Builder Framework Settings:

<img width="383" alt="Screen Shot 2021-06-01 at 2 36 45 PM" src="https://user-images.githubusercontent.com/84725053/120373814-cd720380-c2e6-11eb-8873-7a04896a6a02.png">

**Comment by premanshup** [comment]
@ceendicott Thank you for this requesting this improvement.
We have discussed with our designing team and we are moving forward to move typography from addon to free theme.
Task - https://wp-astra.atlassian.net/browse/AST-578
This improvement will be included in the upcoming 2-3 releases.
Thank you!
