### ISSUE TITLE
Flex CSS causing visual issue on LifterLMS checkout screen

### ISSUE THREAD

**Issue by thomasplevy** [brainstormforce/astra#2873]
### Describe the bug:

Visual issues on LifterLMS checkout screen, also reported at Also reported to LifterLMS at https://github.com/gocodebox/lifterlms/issues/1663

### To reproduce:

+ Visit a LifterLMS checkout screen
+ the fixed height of the second column causes the border to display below the content

### Expected behavior:

Border shows up below content (not behind it)

### Screenshots:

![Screenshot_2021-06-17_18-00-19](https://user-images.githubusercontent.com/1290739/122490048-e55baf80-cf95-11eb-934b-985cfa764f27.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.7.2

### Astra Theme version:

3.6.0

**Comment by sagarb90** [comment]
Hello @thomasplevy,
 
Thank you for reaching out to us.

We are able to replicate this issue and we will fix it in our upcoming release.
We have also added a task for the same - https://wp-astra.atlassian.net/browse/AST-588

Thank you.

**Comment by thomasplevy** [comment]
Thanks @sagarb90!

**Comment by shubhw12** [comment]
@thomasplevy 

Greetings for the day!

We have addressed this scenario in one of our recent updates.

I am closing this issue now.

Thank you.

**Comment by thomasplevy** [comment]
Thanks @shubhw12 !
