### ISSUE TITLE
Rank Math - Breadcrumbs integration improvement

### ISSUE THREAD

**Issue by surajv** [brainstormforce/astra#2878]
### Is your feature request related to a problem? Please describe.
If the user enables Rank Math Breadcrumbs from Astra's customizer setting and if breadcrumbs in Rank Math are disabled(default value), then it shows the blank space https://i.rankmath.com/SXWxJt

### Describe the solution you'd like
Adding this code in the theme `add_theme_support( 'rank-math-breadcrumbs' );` will automatically enable the breadcrumbs in Rank Math settings.

**Comment by premanshup** [comment]
Hello @surajv 
Thank you for reaching out to us.
We have added a task for this - https://wp-astra.atlassian.net/browse/AST-586
This improvement will be released in next version ( v3.7.0 ) of theme.
Thank you
