### ISSUE TITLE
mobile menu is shortly visible in the desktop view

### ISSUE THREAD

**Issue by JidWictut** [brainstormforce/astra#2880]
Hello,
since the last update, the mobile menu is shortly visible in the desktop view (see picture).

With kind regards

![flashing menu](https://user-images.githubusercontent.com/65712457/122673780-59829700-d1d2-11eb-9135-0321e6632929.png)

**Comment by premanshup** [comment]
@JidWictut Thank you for reaching out to us. Can you please follow the instructions mentioned in this doc - https://wpastra.com/docs/clear-astra-cache/. Let us know if this fixes your menu.

**Comment by JidWictut** [comment]
Hello @premanshup,
I followed the instructions and the problem persisted. After I cleared the cache of Autoptimize the problem was solved.
Thanks for the quick reply.

**Comment by premanshup** [comment]
@JidWictut Great! Closing this issue.
Please open a new issue if you face any problems in the future.
