### ISSUE TITLE
Elementor error with the 404 page

### ISSUE THREAD

**Issue by stylethemes** [brainstormforce/astra#291]
so i use the Header Footer Elementor plugin to design the header and footer in my theme but when i go to the 404 page i find this error and it shows only on the 404 page the other pages look fine
![1](https://user-images.githubusercontent.com/26869625/32995051-4692908c-cd67-11e7-973e-31e8388983c2.png)

![2](https://user-images.githubusercontent.com/26869625/32995055-5012bd1c-cd67-11e7-9fa8-da970af74a8a.png)

![3](https://user-images.githubusercontent.com/26869625/32995056-5461df42-cd67-11e7-9181-109837c9c949.png)

NB im using the latest version of elementor and header Footer Elementor

**Comment by Nikschavan** [comment]
Closing in favor of https://github.com/Nikschavan/header-footer-elementor/issues/50
