### ISSUE TITLE
Bug Title ...

### ISSUE THREAD

**Issue by jarrodxyz** [brainstormforce/astra#3023]
`<hr>` tag defaults to margin:0 in main.css. Gutenberg shows the `<hr>` element centered, but after save/publish the `<hr>` is then left-aligned because of the 0 margin. Behaviour of Gutenberg and live should be consistent.

**Comment by thebengalboy** [comment]
Hello @jarrodxyz 

This is no longer an issue or has been resolved over time. I'm going to close this. However, if you find the issue on your end, please let us know.

Thanks
