### ISSUE TITLE
Comment form html tags label duplicated

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#3526]
Please see the attached screenshot. The comment form "website" field has two nested labels, of which one can be remove. That is a bug
![Screenshot from 2021-10-19 20-30-10](https://user-images.githubusercontent.com/6888294/137970202-019f913d-8bc1-4f65-919c-0f710d4cd1be.png)

**Comment by thebengalboy** [comment]
Closing the issue as this has been already solved- https://d.pr/i/DTwyNf
