### ISSUE TITLE
Keep base font size consistent

### ISSUE THREAD

**Issue by CGTS** [brainstormforce/astra#3527]
### Describe the bug:
The base font size is dropped from 16px to 91.2% through media queries in the Astra theme. 

### Expected behavior:
The base font size should stay consistent at all times. The shift to a smaller font affects all custom css using rem units. The change forces the user to either write unneeded css to overwrite the html, force the use of px units, or add additional styles to address the font size changes.

**Comment by thebengalboy** [comment]
Please use Astra version 4.0.0, this is solved now. Closing the issue.
