### ISSUE TITLE
Multiple search buttons when no page content found

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#3532]
When there is a page found, but it has no posts content, then two search buttons are shown. One with an icon, one with a text. The one with the icon is too large:

![image](https://user-images.githubusercontent.com/6888294/138053458-5aa5f3e0-d464-4431-b49b-d9a5ff05eafa.png)

You can easily reproduce with:
* Create a new user with no posts written
* Go to `/author/username` and see the same as the screenshot above.

Tested with version 3.7.3

**Comment by thebengalboy** [comment]
Closing the issue as this has been solved already- https://d.pr/i/Sg2MXm

**Comment by NicoHood** [comment]
Correct!
