### ISSUE TITLE
Primary Menu - Menu Font Settings Don't Revert

### ISSUE THREAD

**Issue by ceendicott** [brainstormforce/astra#3569]
### Describe the bug:
I should be able to revert (or clear) the Menu Font styling to default under Header Builder -> Primary Menu -> Design -> Menu Font. Upon changing the font size there is no way to revert to the default/inherit setting and no icon. There is a revert icon for Line Height but clicking that revert icon does not revert to the default or clear the setting (not sure what the right terminology would be for that behavior). It does revert to the last setting but it doesn't clear the setting/restore to default.

### To reproduce:

Modify font settings under Header Builder -> Primary Menu -> Design -> Menu Font

### Expected behavior:
To clear or restore the menu font settings to the theme default settings upon clicking the revert icon.

### Isolating the problem:
- [ X ] This bug happens with no other plugins activated
- [ NA ] This bug happens with a default WordPress theme active
- [ X ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Astra Theme version:
3.7.3

**Comment by thebengalboy** [comment]
This is solved with version 4.0.0.
