### ISSUE TITLE
Primary Menu - Menu Font - Can't set a fractional line height.

### ISSUE THREAD

**Issue by ceendicott** [brainstormforce/astra#3571]
### Describe the bug:
Under the line height setting for the Primary Menu menu font in customizer you are unable to set a fractional line-height (ie 1.25 em). It acts like it accepts the input but when you click away from the box it reverts to a whole number. You are also unable to set a line height in px. This is strange as the default setting is 70px.

### To reproduce:
Go to Customizer > Header Builder > Primary Menu > Menu Font > Line Height and attempt to enter in a fractional line height (ie 1.25em). 

### Expected behavior:
You should be able to set a fractional line height in em OR be able to specify a specifc px setting as the default is 70px.

### Screenshots:
n/a

### Isolating the problem:

- [ X ] This bug happens with no other plugins activated
- [ NA ] This bug happens with a default WordPress theme active
- [ X ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Astra Theme version:
3.7.3

**Comment by thebengalboy** [comment]
This is solved with version 4.0.0.
