### ISSUE TITLE
3.7.4 Gutenberg layout issues

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#3604]
### Describe the bug:
I upgraded my astra theme to 3.7.4 and [applied the mentioned filter](https://wpastra.com/docs/gutenberg-ui-improvements-with-astra/):

```
add_filter( 'astra_get_option_improve-gb-editor-ui', '__return_true' );
```

Now the editor sometimes looks really weird. I know that some of the old block now behave different and I need to modify them. But this (screenshot) is really not what I would expect:

![grafik](https://user-images.githubusercontent.com/6888294/139123528-a376c3a1-99d1-47db-b30e-8456acf413fc.png)

### To reproduce:
1. Create some content with an older version. Headings, text, text + pictures. It might be relevant, that there is a read more tag in my post, as all text afterwards is aligned incorrect?
2. Upgrade version
3. Add the filter
4. Reedit the post and you will see errors, like my screenshot

### Expected behavior:
All Aligned correct

### Isolating the problem:
Sorry, aint got time to test this.

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Astra Theme version:
3.7.4

**Comment by ElectricFeet** [comment]
Apologies, I just filed another similar bug issue before reading this. In [that issue](https://github.com/brainstormforce/astra/issues/3639), I detail the CSS that seems to cause the problem.

**Comment by NicoHood** [comment]
Thanks for reporting!

**Comment by NicoHood** [comment]
Will this get fixed? It is SUPER annoying!

**Comment by NicoHood** [comment]
What about this issue? You introduced new layouts and did not manage to fix them within multiple month!

**Comment by imnavanath** [comment]
Hi @NicoHood,

We have replied for this same query here, please go through once  - https://github.com/brainstormforce/astra/issues/3639#issuecomment-1002909261

The scenario & cases are also mentioned over there.

Thanks & Regards,

**Comment by NicoHood** [comment]
I still dont understand. Why is the text different intended than the headline? That looks broken. Look at my screenshot.

**Comment by NicoHood** [comment]
I also want to note, that whole layouts broke with this change. But even worse, you cannot fix them. I took the "mountains" starter site from astra templates library.

## Before

Editor:
![grafik](https://user-images.githubusercontent.com/6888294/148391198-7ee2fb15-9c80-49cd-8671-5364bbce9130.png)

Final site:
![grafik](https://user-images.githubusercontent.com/6888294/148391250-9a3ae91a-219e-4b37-a4ae-db10e747928e.png)

## After

Editor:
![grafik](https://user-images.githubusercontent.com/6888294/148391317-4be7b22c-2e2b-4d80-89d7-4b63a285f170.png)

Final site:
![grafik](https://user-images.githubusercontent.com/6888294/148391337-881ab266-08ac-4f1d-adf9-bfe605260896.png)

There is **no way to enlarge the 3 image columns**. They are just always so small, not chance to fix this behavior. However I this might be an even different issue than originally reported, as this also affects the final webpage, not only the editor.

@imnavanath can you please take a closer look at those upgrades pages?

**Comment by NicoHood** [comment]
I just noticed, that the width settings button is missing for the columns:
![grafik](https://user-images.githubusercontent.com/6888294/148391915-4585c026-10cc-4050-b431-02c584f63177.png)

Looking at [your video](https://share.bsf.io/Apuxn6pr) there is one at your place. Maybe the `astra_get_option_improve-gb-editor-ui` filter is missing to enable this option?

**Comment by NicoHood** [comment]
I want to note, that I found one more, **but different** issue, reported here:
https://github.com/brainstormforce/astra/issues/3639#issuecomment-1006605078

I cannot set the width for all gutenberg blocks, but in your video you could. I guess that is one issue with the upgrade. My reported issue here affects the visual display in the editor, those two issues could be closely related, even though **they are not the same.**

**Comment by NicoHood** [comment]
This issue has been fixed with the most recent update. You need to apply new fitlers though:
https://wpastra.com/docs/improved-block-editor-experience/#few-more-filters

Be aware that the new defaults filter will pull you in some... new defaults. This introduced new bugs to me, that I've already reported and it requires to have a very careful check at which pages have been broken and need manual re-setting the values.
