### ISSUE TITLE
Very vague CSS affecting multiple elements, causing multiple problems 

### ISSUE THREAD

**Issue by ElectricFeet** [brainstormforce/astra#3749]
### Describe the bug:
New CSS added in latest release breaks various aspects of site content because it is too unspecific. 

### To reproduce:
Line 745 of inc/class-astra-dynamic-css.php ( see [diff](https://github.com/brainstormforce/astra/commit/7e17038847edd61c353c36b232b82a516f450d14) ) introduces (once processed):

```
.wp-block-group__inner-container :last-child {
   margin-bottom: 0
}
```
### Expected behavior:
A CSS change shouldn't affect user's content by changing margins like this.

### Actual behavior:
The CSS introduced means that **_anything_** inside a WP group gets its last-child's bottom margin changed, with unpredictable results. 

In my case, the content on my sites makes extensive use of the WP block columns and grouping and, for example, the newly-inserted CSS messes up alignment of all flex items that are set to justify-content vertically, as the margin on the last item is no longer equal to the others.

And what makes it worse is that it affects not only the very last child but all the nested last-children above it. So if you have two images (one of which is the last-child) inside a last column, inside the last columns block, inside a group, then **_all_** of those items get their margins changed(!), because they are all last-children of one sort or another.

Unfortunately, there's no easy way to "undo" the CSS with my own, because it targets so many separate items, all of which would need to be individually targeted.
 
### Isolating the problem:
- [Y ] This bug happens with no other plugins activated
- [N ] This bug happens with a default WordPress theme active No: it's an astra bug
- [Y ] I can reproduce this bug consistently using the steps above

### WordPress version:
WP 5.8.2

### Astra Theme version:
3.7.5

### Suggested solution:
This CSS should be much more specific -- targeting only the items that need to be targeted and not just **_any_** :last-child in any wp block group. It's not at all clear to me why this change was introduced. I'm happy to help make this more specific to the problem you were trying to solve, if you can tell me the reasoning behind the change.

N.B.: this may be one of the reasons users are reporting (on wordpress.org) formatting issues on their sites since the last release. It took me an afternoon to pin down what was happening on my sites -- it's not easy to find.

**Comment by ElectricFeet** [comment]
And the more I look at this, the more it looks like an accidental copy/paste...

**Comment by ElectricFeet** [comment]
In the meantime, it can be removed with the following in a child theme's functions.php:

```
apply_filters( 'astra_theme_dynamic_css', $parse_css );
add_filter('astra_theme_dynamic_css', 'my_remove_selected_css');
function my_remove_selected_css($parse_css) {
    $parse_css = str_replace(".wp-block-group__inner-container :last-child,", "", $parse_css);
    return $parse_css;
}
```

**Comment by imnavanath** [comment]
Hi @ElectricFeet,

Thank you for reaching out to us.

The filter you provided can be considered as a workaround.

We have added this CSS intentionally. The reason behind adding this CSS is to manage the same overall top and bottom spacing for the Group block.

By default from the theme, we have added margin-bottom: 1.6em; for the paragraph. Due to this inside group block, the top and bottom overall spacing become inconsistent.

Screenshot - https://share.bsf.io/E0uKveR9 

Here is an illustration about this case -

After removing this CSS - https://share.bsf.io/Z4urBG51 (see the difference in spacing)
With this CSS - https://share.bsf.io/7KuAlW00 (same spacing from top-bottom)

These inputs are provided by our design team to make sure we provide consistent design for the users with blocks.

I hope that clarifies your query.

Thanks & Regards.

**Comment by ElectricFeet** [comment]
Hi @imnavanath. Thanks for replying. 

I fully understand your need to have CSS to adjust the look of the theme in your case. The issue here, however -- and it still is an issue (should not be closed) -- is that the CSS that is used to correct the situation is way too unspecific. Using `:last-child` on its own will affect multiple items all at once. 

Just to give one (real, but sanitized) example:

```
<div class="wp-block-group">
    <div class="wp-block-group__inner-container">
        <h2> ... </h2>
        <div class="wp-block-columns">                                      <<<< this is affected
            <div class="wp-block-column">
                <p> ... </p>
                <p> ... </p>
                <p> ... </p>                                                <<<< this is affected
            </div>
            <div class="wp-block-column">                                   <<<< this is affected
                <div class="wp-block-columns">
                    <figure class="wp-block-image size-full"> ... </figure>
                    <figure class="wp-block-image size-full"> ... </figure> <<<< this is affected
                </div>
                <div class="wp-block-column">                               <<<< this is affected
                    <figure class="wp-block-image size-full"> ... </figure>
                    <figure class="wp-block-image size-full"> ... </figure> <<<< this is affected
                </div>
            </div>
        </div>
    </div>
</div>
```
Every single one of those items indicated above is a last child of _something_ within the block group. _Everything_ becomes misaligned. And it gets even worse if you try align any of those items to `flex-end` or justify them with `space-between` etc. 

Specificity is fundamental here. If you want the CSS to affect the last paragraph in a block group, then `p:last-child` should be used, not `:last-child`. Another approach is to use` >` to make sure that you are only affecting the immediate children. Even better, use both approaches. Ideal here would be:
```
.wp-block-group__inner-container > p:last-child {
   margin-bottom: 0
}
```

Bringing this down to the specific case is really important. Otherwise, it will trip people up all over. Once over-broad CSS is used like this, it can become a nightmare to manage, with fixes upon fixes later on.

**Comment by ElectricFeet** [comment]
p.s. can someone re-open this?

**Comment by imnavanath** [comment]
Hi @ElectricFeet,

Thanks for your insights.

I'm opening this issue now again. And after checking this case & discussion with team, I'll update status here.

**Comment by ElectricFeet** [comment]
Thanks @imnavanath , much appreciated :)

**Comment by NicoHood** [comment]
Will this eventually get fixed along with the other layout issues introduced with this update?
https://github.com/brainstormforce/astra/issues/3604
https://github.com/brainstormforce/astra/issues/3639

**Comment by thebengalboy** [comment]
I'm closing the issue as this should be solved now.
