### ISSUE TITLE
The false XSS filters

### ISSUE THREAD

**Issue by hokoo** [brainstormforce/astra#396]
Who can to explain in details [WHAT is the code](https://github.com/brainstormforce/astra/blob/master/inc/blog/blog-config.php#L244)
```
		$categories_list = get_the_category_list( esc_html__( ', ', 'astra' ) );

		if ( $categories_list ) {
			$categories = sprintf(
				esc_html( '%1$s' ), $categories_list
			);
```
How does it `esc_html( '%1$s' )` protect against XSS??
And what is the point to escape the result of `get_the_category_list()`?
And what is it `esc_html__( ', ', 'astra' )`? We translate the comma? wow

**Comment by Nikschavan** [comment]
Hello @hokoo,

I have just sent a [PR](#404) to address. I have now reduced the escaping when displaying the category list and the tags list.

About `esc_html__( ', ', 'astra' )` - Yes, the `,` can be different in many languages eg [Romania](https://cl.ly/p1HX) so it needs to be translated.

**Comment by Nikschavan** [comment]
Closing this as #404 is now merged.
