### ISSUE TITLE
LifterLMS use my CSS for the sidebar styling

### ISSUE THREAD

**Issue by reachadam** [brainstormforce/astra#399]
Here is an example https://www.wpcrafter.com/course/elementor-essentials/

See how the CSS makes the lesson titles smaller, its better for a sidebar. Also, I reduced the spacing and added a separator. It makes it look a lot cleaner. 

I am using the beta with the beta integration.

**Comment by sujaypawar** [comment]
@dineshchouhan - Let's take some inputs from design team and style sidebars.

**Comment by Nikschavan** [comment]
Closing this task as this is already fixed in v1.3.3 of the theme.
