### ISSUE TITLE
Change Logs

### ISSUE THREAD

**Issue by gravnetic** [brainstormforce/astra#4088]
I am getting really tired of hunting down your changelogs.  You just released a minor version which indicates there could be some breaking changes.  3.7.X.  I really do not appreciate searching around the web, when ever other theme and plugin implements changelog notes within the release that I can read right inside WordPress.

**Comment by premanshup** [comment]
@gravnetic v3.7.7 has all the fixes only related to WP 5.9. WP 5.9 is going to be released today. By releasing this version we have ensured that Astra is fully compatible with WP 5.9. WordPress has made some changes in the controls like Color Picker, Gradient Picker. Astra internally uses these controls in the customizer. This is the reason we have released this update. It was released yesterday, till now we have received no issues with the update. I would request you to please update your theme to v3.7.7 to make it compatible with WordPress 5.9 version.
