### ISSUE TITLE
Enable Button Block Spacing Wordpress Feature in theme.json

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4135]
It is as easy as:
https://github.com/WordPress/gutenberg/pull/34546#issuecomment-1040919071
https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#what-is-blockgap-and-how-can-i-use-it

![](https://user-images.githubusercontent.com/63313398/132585074-91602c8d-90bb-419a-8bfb-851c23cfe296.gif)

**Comment by aapatre** [comment]
I've addressed the issue using PR #4191 

cc: @NicoHood

**Comment by imnavanath** [comment]
As we have implemented solution for this, closing this issue. More details are here - https://github.com/brainstormforce/astra/pull/4191#issuecomment-1197633707
