### ISSUE TITLE
please add an hook to disable <link rel="profile" href="https://gmpg.org/xfn/11" />

### ISSUE THREAD

**Issue by rebelcode-xr** [brainstormforce/astra#4172]
### Is your feature request related to a problem? Please describe.
I would like to remove the tag `<link rel="profile" href="https://gmpg.org/xfn/11" />` to prevent GDPR violations:
https://www.violating-gdpr.com/

<img width="320" alt="image" src="https://user-images.githubusercontent.com/63522951/157122110-b8b5f99c-f514-4e03-a5e3-c1f3055841a3.png">

### Describe the solution you'd like
Please add an hook to disable it, like in this other theme:
https://kriesi.at/support/topic/removing-the-link-to-httpgmpg-orgxfn11-in-enfold/

### Describe alternatives you've considered
Better remove the tag if it's not really necessary or disable it by default (opt-in).

**Comment by imnavanath** [comment]
Hi @rebelcode-xr, 

Thanks for reporting this.

We have fixed the issue in this PR - https://github.com/brainstormforce/astra/pull/5038 And this will be release in next planned 4.2 version.

You can use this filter to disable the profile link & to fix the GDPR issue - 
```
add_filter( 'astra_header_profile_gmpg_link', '__return_false' );
```

Best regards,
Navanath & Astra team

**Comment by rebelcode-xr** [comment]
awesome, thanks! 🙏
