### ISSUE TITLE
Documentation typos in development-workflow.md

### ISSUE THREAD

**Issue by aapatre** [brainstormforce/astra#4190]
The development workflow doc has following grammatical/spelling errors:

- Misspelled ['WordPress.org'](https://github.com/aapatre/astra/blame/master/docs/development/development-workflow.md#L14)
- Misspelled ['requests'](https://github.com/aapatre/astra/blame/master/docs/development/development-workflow.md#L16)
- Grammatical error on [L19](https://github.com/aapatre/astra/blame/master/docs/development/development-workflow.md#L19)
- Misspelled 'scenarios' on [L39](https://github.com/aapatre/astra/blame/master/docs/development/development-workflow.md#L39) and [L42](https://github.com/aapatre/astra/blame/master/docs/development/development-workflow.md#L42)

**Comment by aapatre** [comment]
I've raised PR #4189 for the same

**Comment by imnavanath** [comment]
Thanks @aapatre for the contribution. 😃
