### ISSUE TITLE
Use Astra LifterLMS syllabus style with shortcode?

### ISSUE THREAD

**Issue by reachadam** [brainstormforce/astra#422]
LifterLMS has a shortcode system, https://lifterlms.com/docs/shortcodes/

I am not fond of the default lesson layout and was thinking of adding the lifterlms syllabus shortcode via Astra custom layouts to put the Astra styled syllabus layout at the bottom of every lesson. 

Needless to say it didn't work out so great, lol. 

The lifterlms shortcode for the syllabus, when rendered doesn't show the Astra design. Is there a way to get that the lifterlms shortcode to show the Astra styled one?

**Comment by reachadam** [comment]
You guys made some improvements here in the last update, but its still needs a little work. Here is a screenshot of how the shortcode now looks after your improvements last week. 
<img width="1226" alt="screenshot 2018-02-06 18 30 04" src="https://user-images.githubusercontent.com/20959226/35895382-0c026da0-0b6c-11e8-9e2b-c3875e6f9811.png">

Here is how the versions that is on the course index page looks
<img width="1227" alt="screenshot 2018-02-06 18 32 59" src="https://user-images.githubusercontent.com/20959226/35895417-2d4d61ea-0b6c-11e8-81ed-798596d2098f.png">

See the check placement. I think it would be a huge improvement to move it to the left for the shortcode version because it makes the syllabus more condensed (this is good).

**Comment by Nikschavan** [comment]
Hello @reachadam We have now got the styling/layout from shortcodes looking similar when used from shortcode and LiftterLMS's layouts.

Thank you for the report and suggestions, They are always appreciated :)
