### ISSUE TITLE
type="button" not set on <button id="menu-toggle-close" class="menu-toggle-close" aria-label="Close menu">

### ISSUE THREAD

**Issue by lydenyardley** [brainstormforce/astra#4266]
### Describe the bug:
The default type for `<button>` is submit (not type="button" as one might expect).

The best way to avoid unexpected surprises is to always explicitly set a type on `<button>`s.

### To reproduce:
Simply observe the code being output for the flyout menu close button

### Expected behavior:
Add `type="button"` attribute to `<button id="menu-toggle-close" class="menu-toggle-close" aria-label="Close menu">`

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Latest

### Astra Theme version:
Latest

**Comment by thebengalboy** [comment]
Hi @lydenyardley 

I'm closing this issue considering this has been [solved already](https://github.com/brainstormforce/astra/pull/4268/files). Feel free to reopen it in case you have any feedback about the fix.

Thanks
