### ISSUE TITLE
LifterLMS Course and Lesson widget areas not in customizer

### ISSUE THREAD

**Issue by chrisbadgett** [brainstormforce/astra#431]
LifterLMS course and lesson sidebars don't display in the customizer widget areas
<img width="1432" alt="customize__leadership_course_ _astra_lifterlms_test" src="https://user-images.githubusercontent.com/12163552/35766856-f5d2b3d4-08ad-11e8-8b99-d944553f67d2.png">
LifterLMS has a Course sidebar widget area and lesson sidebar widget area

#429 #

**Comment by dineshchouhan** [comment]
Hello @chrisbadgett,
I'll check sidebar compatibility for LLMS, it's fixed will get a release in next update.

**Comment by Nikschavan** [comment]
Closing this in favor of https://github.com/gocodebox/lifterlms/issues/448
