### ISSUE TITLE
LifterLMSProgress Bar % css appears off

### ISSUE THREAD

**Issue by chrisbadgett** [brainstormforce/astra#432]
Progress bar % css appears off in the LifterLMS sidebar 

<img width="416" alt="internet_marketing_course_ _astra_lifterlms_test" src="https://user-images.githubusercontent.com/12163552/35766890-854a03a0-08ae-11e8-8845-49a42bd89fce.png">

**Comment by dineshchouhan** [comment]
Hello @chrisbadgett,
This is a small glitch, this will get fixed in next release.

**Comment by Nikschavan** [comment]
@chrisbadgett This is fixed already in the latest stable release. We are updating the theme to v1.3.3 very soon with few more fixes related to LifterLMS.
