### ISSUE TITLE
[Feature suggestion] Woo Category Descriptions on shop homepage

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#438]
Currently you can see category description on the category archive page, but not on the shop homepage.

### Example on fake test shop

Shop home: https://www.minddump.nl/shop/ Nothing is displayed under “Op afstand” and “Persoonlijk”.
FYI: Also the shadow-styled boxes of the products are not applied to the categories.

Shop category archive page: https://www.minddump.nl/cat/persoonlijk/
Category description is present: “Persoonlijker dan dit wordt het niet.”

**Comment by Ver3** [comment]
Is there a PHP-snippet to do this in the meantime (until hopefully, one day Astra implements this)?

**Comment by Ver3** [comment]
**I got this back from support just now:**

There is no such option is available to show the category description on the shop page.

You can add following code snippet to your child theme's functions.php file to add Category Description to the shop page. 

We are going to release the theme update today itself after updating the theme the following code snippet doesn't require any style. As of now if you add this code snippet then you might need to style this description as per your requirement. 

```
add_action( 'wp', 'single_product_variable_loggedin_user' );
function single_product_variable_loggedin_user() {
add_action( 'woocommerce_after_subcategory', 'astra_product_archive_description' );
}

/**
* Show Category Description on shop page
*
* @param object $category     Category object
*/
function astra_product_archive_description( $category ){

$cat_id=$category->term_id;
$prod_term = get_term($cat_id,'product_cat');
$description = $prod_term->description;
echo '<div class="ast-woo-shop-product-description"><p>'.$description.'</p></div>';
}
```

Not sure if I'm reading this correctly, but it seems this is coming to the theme today by default.

**Comment by Nikschavan** [comment]
In the upcoming update we will be fixing the CSS bug that is making the category/subcategory title go below the description in your case - https://cl.ly/pPiD

You will still have to add this php snippet to display this description though.

**Comment by Ver3** [comment]
Thank you for your reply @Nikschavan. Just curious, why not included this in Astra Core? It seems like such an obvious feature to include. 

Cheers

**Comment by Nikschavan** [comment]
My current thoughts are - 

- Since this has been off from the initial design, Turning it on automatically in an update is a backward compatibility breakage. People using categories on their sites with current layout will automatically start seeing the descriptions in their completed websites.
- This should come as an option which will be by default off, but right now there does not seem to be other settings specifically for the archives.

I have added this to our list to consider the best approach for this.

**Comment by Ver3** [comment]
Ok, thank you @Nikschavan I'll wait for the update before proceeding.

**Comment by Nikschavan** [comment]
Astra Pro v1.2.0 did update fix this CSS breakage when the description is added using the filter so you can use this filter on your site.

We do have few more improvements to the category display on the shop page which will provide more style options in future updates of Astra Pro.

**Comment by Ver3** [comment]
Thank you @Nikschavan I've just tried it out and it works now. Cheers.

**Comment by Ver3** [comment]
@Nikschavan  It works great on our corporate site too (ignore the design, still working on it)

One question though: For products, there is this awesome shadow hover effect. But not for categories? How do I get them the same (for consistency).

Cheers

Ps. no hurry, it's not a bug, just weird.
