### ISSUE TITLE
[Feature suggestion] WooCommerce “missing” from these Customizer menu’s

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#439]
- Typography
- Colors & Background
- Buttons

This also results in not being able to adjust the typography of the "Off Canvas Sidebar”.

This was easily fixed by using this CSS, but doing it via customiser would be so much better.

```
.woocommerce h2 {
    font-size: 1.2em;
}
```

**Comment by Nikschavan** [comment]
Thank you for the report @Ver3!

Astra Pro v1.2.0 introduced the missing options for the WooCommerce addon [Changelog](https://wpastra.com/changelog/astra-pro-addon/#post-24873)

**Comment by Ver3** [comment]
Awesome work, thank you so much.

One thing seems to remain though, how to style the "Off Canvas Sidebar”? Shall I create a new issue for this?
