### ISSUE TITLE
[Feature suggestion] Multiple Custom Menu Items for Header

### ISSUE THREAD

**Issue by VerdiH** [brainstormforce/astra#440]
Currently you can select things like Woocommerce (cart) **OR** Search, but not both.

For many shops you'll need both without having to resort to above or below header.

**Comment by shubhw12** [comment]
@VerdiH 

Thank you for the feature suggestion.

We will soon be able to fulfill the above requirement in the upcoming updates of Astra.

We really appreciate your concern about our product.

Thank you
