### ISSUE TITLE
Incorrect width applied to paragraphs

### ISSUE THREAD

**Issue by cdils** [brainstormforce/astra#4407]
## Problem:

The wide width size (`--wp--custom--ast-wide-width-size`) is applied to paragraphs, while other page elements are set to `--wp--custom--ast-content-width-size`.

The result is odd alignment where `<p>` elements are at the wide width while other elements such as headings are set to content width. (see screenshot)

![Screen Shot 2022-06-15 at 5 07 10 PM](https://user-images.githubusercontent.com/3099408/173962305-1f9b1e96-7cb4-4b0d-8a0b-e389ee0513e6.png)

## Expected behavior:

Paragraphs should inherit `--wp--custom--ast-content-width-size` unless explicity set to use wide width.

## Possible fix:

Remove `.entry-content[ast-blocks-layout] > p` from this selector list:

https://github.com/brainstormforce/astra/blob/45cf32b9103ae40104f9b4c1df740ad1f2411914/inc/dynamic-css/block-editor-compatibility.php#L274-L276

## My environment:

Astra 3.8.2
WP 6.0
Gutenberg 13.4.0

**Comment by paride** [comment]
I didn't try the proposed fix, but I can confirm the described behavior.

**Comment by paride** [comment]
Looks like that lowering the container width from 1200px (what I had by default) to 910px makes the problem go away (altering the width of course), or at least hides it.

**Comment by imnavanath** [comment]
Hi [paride](https://github.com/paride),

Thanks for reaching out to us.

We have already made this improvement in our block editor V2 enhanced experience version i.e., v3.8.3.

Have a look at this document - https://wpastra.com/docs/improved-block-editor-experience/#few-more-filters

To enable this improvement on your end please add this filter in your child theme - 
```
add_filter( 'astra_get_option_wp-blocks-v2-ui', '__return_true' );
```

**Note:** This filter also includes block editor-level improvements, so before you go live, take an overview of your pages on the front end, just a safer side.

I hope that resolves your query. Please let us know if there is anything.

Thanks & Regards!
