### ISSUE TITLE
[Feature suggestion] Improved Search Bar + Full screen search option

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#441]
Problem: When using search, you can still see the menu items below it. This might be due to some setting I have not yet discovered, but by default, this does not look good.

Suggestion: Add the ability to style the search bar and maybe even add the option to have a full-screen search.

**Comment by Nikschavan** [comment]
Astra Pro's Next update `v1.5.0` will have Search Styles in the customizer.

**Comment by Ver3** [comment]
That's great news! Thanks for letting me know Nik, feel free to close this one.
