### ISSUE TITLE
[Feature suggestion] Search customizer settings

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#442]
I’ve seen a theme that had three tabs in the top of the customizer settings (like Elementor) “Content”, “Style” and “Advanced”. Awesome idea.

But having search in the top of customizer settings could also really speed up the developing process.

I’ve never seen this being done though and suspect there is a good reason for it. I thought I’d mention this one anyway.

Cheers!

**Comment by Nikschavan** [comment]
Yes, This would be a great idea. I did give this a try a few months back to add search in the customizer - https://cl.ly/pJtF 

Although this does not yet show accurate search results and is not highly reliable. I will try to have a look at this project once again, try to improve this. 

You can this this out from here - https://github.com/Nikschavan/customizer-search

**Comment by Ver3** [comment]
@Nikschavan Awesome example, thank you! This is exactly what I mean.

Would be great if this was one of the modules you can enable or disable in Astra. Such a time saver.

**Comment by Nikschavan** [comment]
Hey @Ver3 

I just updated the plugin [Customizer Search](https://wordpress.org/plugins/customizer-search/) on W.org with a rewrite of the search logic now this should return correct results. This also works with all the themes so I think this should be a separate plugin rather then being a part of Astra. Let me know your thoughts on this.

I will close this issue in favor of the [GitHub repo for Customizer Search](https://github.com/Nikschavan/customizer-search) do let me know any suggestions related to that plugin.

**Comment by Ver3** [comment]
Just left a review, and I'll follow the repo. Thank you for this one! I just tested it, and love it. Still think it should either be part of the theme as an optional module OR... there should be a "BF-tab" in Astra settings promoting all other BF-plugins. Now you just don't know the awesome things BF has put out there.

Thanks again, cheers!
