### ISSUE TITLE
AMP compatibility issue

### ISSUE THREAD

**Issue by SEOsakht** [brainstormforce/astra#4481]
### Describe the bug:
AMP incompatibility
"ast-blocks-layout" attribute causes this issue

### To reproduce:
Just install and activate astra theme then install and activate AMP plugin

### Screenshots:
[
    {
        "url": "http://localhost:8080/a/111/",
        "type": "is_singular[post]",
        "label": "Post",
        "amp_url": "http://localhost:8080/a/111/?amp=1",
        "validation_errors": [
            {
                "code": "DISALLOWED_ATTR",
                "element_attributes": {
                    "class": "entry-content clear",
                    "ast-blocks-layout": "true",
                    "itemprop": "text"
                },
                "node_name": "ast-blocks-layout",
                "parent_name": "div",
                "type": "html_attribute_error",
                "node_type": 2,
                "sources": [
                    {
                        "type": "theme",
                        "name": "astra",
                        "file": "inc/class-astra-loop.php",
                        "line": 186,
                        "function": "Astra_Loop::loop_markup",
                        "hook": "astra_content_loop",
                        "priority": 10
                    },
                    {
                        "type": "theme",
                        "name": "astra",
                        "file": "inc/class-astra-loop.php",
                        "line": 118,
                        "function": "Astra_Loop::template_parts_post",
                        "hook": "astra_template_parts_content",
                        "priority": 10
                    },
                    {
                        "type": "theme",
                        "name": "astra",
                        "file": "inc/template-parts.php",
                        "line": 263,
                        "function": "astra_entry_content_single_template",
                        "hook": "astra_entry_content_single",
                        "priority": 10
                    }
                ]
            }
        ],
        "stale": false
    },
    {
        "url": "http://localhost:8080/a/222/",
        "type": "is_singular[page]",
        "label": "Page",
        "amp_url": "http://localhost:8080/a/222/?amp=1",
        "validation_errors": [
            {
                "code": "DISALLOWED_ATTR",
                "element_attributes": {
                    "class": "entry-content clear",
                    "ast-blocks-layout": "true",
                    "itemprop": "text"
                },
                "node_name": "ast-blocks-layout",
                "parent_name": "div",
                "type": "html_attribute_error",
                "node_type": 2,
                "sources": [
                    {
                        "type": "theme",
                        "name": "astra",
                        "file": "inc/class-astra-loop.php",
                        "line": 173,
                        "function": "Astra_Loop::loop_markup_page",
                        "hook": "astra_content_page_loop",
                        "priority": 10
                    },
                    {
                        "type": "theme",
                        "name": "astra",
                        "file": "inc/class-astra-loop.php",
                        "line": 108,
                        "function": "Astra_Loop::template_parts_page",
                        "hook": "astra_page_template_parts_content",
                        "priority": 10
                    }
                ]
            }
        ],
        "stale": false
    }
]

### WordPress version:
6.0.1

### Astra Theme version:
3.9.1

**Comment by thebengalboy** [comment]
Hello @SEOsakht 

After careful consideration and evaluation of the evolving web standards, we have decided to discontinue our support for AMP. This decision is in line with Google's shift in focus to Core Web Vitals, which have become a more prominent factor in determining website performance and user experience.

As you may be aware, AMP was initially introduced as an initiative to enhance mobile page loading speeds and improve overall user experience on mobile devices. However, Google's recent updates and advancements in web technologies, including the introduction of Core Web Vitals, have led us to reevaluate our approach.

Core Web Vitals, which include metrics such as loading speed, interactivity, and visual stability, have become the new standard for measuring website performance. By prioritizing Core Web Vitals, we aim to ensure that your websites built with the Astra theme continue to provide exceptional user experiences and meet the latest industry standards.

Rest assured, this change will not impact your current websites built with the Astra theme. They will continue to function without any disruption. We just won't be providing any further support or development for AMP further.


We understand that some of you may have relied on AMP for specific requirements, and we apologize for any inconvenience this may cause. However, we firmly believe that this shift in focus will benefit the majority of our users by aligning our products with the latest industry standards and delivering optimal website performance.

Thank you for your continued support and understanding. If you have any questions or concerns, please feel free to reach out to our support team, who will be more than happy to assist you.
