### ISSUE TITLE
Full Width / Stretched not working as it should

### ISSUE THREAD

**Issue by ngustavo** [brainstormforce/astra#4515]
### Describe the bug:
When trying to reproduce stretched header layout as seen in themes [2022](https://wordpress.org/themes/twentytwentytwo/) and [Prime Lawyers](https://websitedemos.net/law-02/), it keeps a padding of 20px around the container instead of stretching it to screen size.

### To reproduce:
1. Install Astra and Astra Child
2. Install Spectra
3. Go to Layout > Customizing
4. Global > Container
5. Select Full Width / Stretched
6. Open a page to see the error

### Expected behavior:
It's expected to be exactly full width, without padding.

### WordPress version:
6.0.1

### Astra Theme version:
3.9.1

**Comment by thebengalboy** [comment]
This issue is no longer present - https://d.pr/i/UqEIuP
