### ISSUE TITLE
Astra Pro Sticky: Site-title CSS overwritten in Mobile/Tablet

### ISSUE THREAD

**Issue by RRSchweitzer** [brainstormforce/astra#4584]
### Describe the bug:
When updating the css for the site-title, specifically for sticky, it seems the CSS from the add-on gets overwritten. Any color your choose gets overwritten with white.  was able to temporarily fix this by adding !importants within. It seems that the media query for mobile and table though take precedence. 

wp-content/plugins/astra-addon/addons/sticky-header/classes/dynamic-css/dynamic.css.php

### To reproduce:
1. Create a header and add a site-title
2. Enable transparent header with sticky header
3. Set the page width to tablet or mobile
4. When you scroll the color chosen for sticky on site-title will not be the one you chose.

### Expected behavior:
The color chosen for sticky site-title should match the one chosen.

### Screenshots:
![image](https://user-images.githubusercontent.com/9876731/188242463-6c53f063-b167-4b37-835a-72fd4ff3733b.png)

![image](https://user-images.githubusercontent.com/9876731/188242549-05a5f5d7-e3d2-43a3-a07f-c366d91d2957.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.0.2

### Astra Theme version:
Version 3.9.1 Pro

**Comment by thebengalboy** [comment]
Hi @RRSchweitzer 

We're on it and will provide an update soon. We appreciate your help and patience.

Thanks

**Comment by GauravKhupse** [comment]
@RRSchweitzer I tried to replicate this issue at my end but it's not reproduced. let me know is there anything is missing.

Please refer to this screencast:- https://share.bsf.io/nOubb14w

Also, Please provide your Astra setting export file so I can import it on my end.

**Comment by r-schweitzer** [comment]
My site title is up up one in the settings..not in the middle option. I didn't like the placement there.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/50628828/195070803-054d7dc2-efd0-4786-8bbf-3821924e58de.png">

**Comment by thebengalboy** [comment]
Hi @r-schweitzer 

You can simply drag and drop the `Site Title & Logo` from Above Header to Primary Header. 

--
We do not monitor this GitHub for support questions. Please [open up a ticket by submitting a contact form here](https://wpastra.com/support/) for support queries or if you any other help. Also, for user to user discussions, [join our Facebook group](https://www.facebook.com/groups/227391647730107/).

**Comment by r-schweitzer** [comment]
Yes, I did drag it and move it but there are more issues. Now the header sticks and I can read it but the colors still don't apply. As you can see in the next screen shot the text is set to black on sticky header but it never changes. If I adjust colors nothing happens. I have to unstick and then restick the header but the color never changes on scroll. Its incredibly buggy

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/50628828/195076477-30cae629-0409-46c9-93b0-17c3c8850e80.png">

**Comment by r-schweitzer** [comment]
It basically never lets go of the title color and will never use the sticky color

> Hi @r-schweitzer
> 
> You can simply drag and drop the `Site Title & Logo` from Above Header to Primary Header.
> 
> -- We do not monitor this GitHub for support questions. Please [open up a ticket by submitting a contact form here](https://wpastra.com/support/) for support queries or if you any other help. Also, for user to user discussions, [join our Facebook group](https://www.facebook.com/groups/227391647730107/).

Why did you close this issue?

**Comment by r-schweitzer** [comment]
@thebengalboy Why was this issue closed? This is still not working correclty

**Comment by thebengalboy** [comment]
Hi @r-schweitzer @RRSchweitzer 

Please accept my apologies for any inconvenience; however, I closed the issue because it is not reproducible at our end. I tried it again by following your guideline, but I was able to edit the title colour. Reference: https://d.pr/i/9cGoF7

I understand that you are somehow having difficulties on your site, and we will undoubtedly help you resolve it. The problem you are facing could be dependent on the site environment or anything else which needs to figure out. Could you please contact our support team by creating a [support ticket here](https://wpastra.com/support/)? Our team will work with you to solve the issues.

Thanks
