### ISSUE TITLE
Elementor Free Deprecated function Error

### ISSUE THREAD

**Issue by rubencodingtel** [brainstormforce/astra#4585]
### Describe the bug:

at top of homepage: Deprecated: Function Elementor\DB::is_built_with_elementor is deprecated since version 3.2.0! Use Plugin::$instance->documents->get( $post_id )->is_built_with_elementor() instead. in /home1/{projectName}/public_html/wp-includes/functions.php on line 5379

### To reproduce:
using Astra with Elementor Free

Astra Version: 3.9.1
Elementor free Version: 3.7.4

### Solution:

search in path: ...wp-content/themes/astra/inc/compatibility/class-astra-elementor.php

At line 262 was:

return Plugin::$instance->db->is_built_with_elementor( $id );

changed it to:

return Plugin::$instance->documents->get( $id )->is_built_with_elementor();

And problem solved.

### WordPress version:
6.0

### Astra Theme version:

3.9.1

### Elemento Free version:

3.7.4

**Comment by thebengalboy** [comment]
Hi @rubencodingtel 

This has been fixed already with the PR #4540

**Comment by thebengalboy** [comment]
Hi @rubencodingtel 

This has been solved and released with the version 3.9.2. I'd request you to update to the latest version if you have not updated yet.

Closing the issue for now. However, if you face the same issue even with the latest version, feel free to reopen it.

Cheers!
