### ISSUE TITLE
Since version 3.9.2 the cart icon has changed.

### ISSUE THREAD

**Issue by Martje65** [brainstormforce/astra#4613]
Since version 3.9.2 the cart icon has changed.

Bring back the 3.9.1 cart icon, because this one just doesn’t look professional – especially with the random border around the icon

![cart icon 3 9 2](https://user-images.githubusercontent.com/112067446/190568636-4828c81b-acf9-4a57-943d-59f3f364e51b.jpg)

**Comment by nathanrodrigues2111** [comment]
Hi, @Martje65 

Thanks for reaching out to us.

For the time being you can use this filter to resolve this on your end. 

`add_filter( 'astra_woocommerce_cart_icon', '__return_false' ); `

to bring it back . 

**Note** : In near future this cart icon will be removed altogether as its already in the deprecated list. 

Please could be answer some of my questions to resolve this issue.
- Which astra version where you previously using . As per your post i am assuming its 3.9.1 is this correct ?
- Have you installed astra-addons plugin : https://wpastra.com/pro/ , I yes then please can you tell me version number. 

I hope this help's you and i await for your reply 

Thanks & Regards!

**Comment by nathanrodrigues2111** [comment]
Hi, @Martje65

Thank you for the quick reply and hope the filter worked for you. For future reference to this filter we will be updating out astra doc with the same. 

Thanks & Regards!

**Comment by Martje65** [comment]
The filter do the job @nathanrodrigues2111

Thanks for the help
