### ISSUE TITLE
Quantity buttons don't get rendered if Header/Footer builder not enabled

### ISSUE THREAD

**Issue by jjcoffee** [brainstormforce/astra#4708]
### Describe the bug:
I have the "Enable Quantity Plus and Minus" option enabled in Customizer->Woocommerce->Misc, but the buttons do not appear, only the extra padding to "make room" for the +/- buttons. 

I looked into it a bit further and realised the JS to insert the buttons isn't getting enqueued in inc/core/class-astra-enqueue-scripts.php as it's wrapped in the condition `if ( true === Astra_Builder_Helper::$is_header_footer_builder_active )`. 

Unless I'm missing something, I can't see why this should be tied to the Header/Footer Builder at all as it's a Woocommerce component and there's no reason to expect it not to work in this scenario.

### To reproduce:
1. Disable Header/Footer Builder in Astra Options
2. Ensure "Enable Quantity Plus and Minus" is enabled in Customizer->Woocommerce->Misc
3. Open any product page, the quantity +/- buttons will not show

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.0.3

### Astra Theme version:
3.9.2

**Comment by SimranChougule1** [comment]
The issue no more exists with the newer versions.
