### ISSUE TITLE
Footer Widgets Dynamic CSS gets duplicated

### ISSUE THREAD

**Issue by rookiegrammer** [brainstormforce/astra#4775]
### Describe the bug:
Multiple duplicated rules for Footer Widgets get written in the Dynamic CSS of Astra.

### To reproduce:
1. Use a Footer Widget in Footer Builder.
2. Change Design Options.
3. Multiple duplicated CSS Rules appear for Footer Widget components like _widget-title_.

### Expected behavior:
No duplicated rules.

### Screenshots:
![image](https://user-images.githubusercontent.com/30749394/203104255-08f6dc6d-92f7-4324-a029-f09782715e7a.png)

### Isolating the problem:
Under the function _astra_fb_widget_dynamic_css_, _astra_widget_dynamic_css( 'footer' )_ is called in a counting loop when it should've been outside the loop. _Astra_Widget_Component_Dynamic_CSS::astra_widget_dynamic_css()_ has its own independent counting loop already.

### WordPress version:
6.1

### Astra Theme version:
3.9.4

**Comment by thebengalboy** [comment]
Thank you for reporting the issue @rookiegrammer ; We'll look into this soon.

**Comment by thebengalboy** [comment]
Solved in the PR: #4900
