### ISSUE TITLE
[Feature suggestion - Nice to have] Dim content on menu hover

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#486]
Ability to activate an option to dim the content when you hover over a menu item (like a lightbox).

- *Reason:* Visitor will have increased focus / better for conversion.
- *Example (just a test site):* https://www.minddump.nl/shop/
- *Urgency:* None, it's just a so-called "nice-to-have", not a "must-have".

**Snippet CSS used:**
```
/* Dim content on menu hover */
#masthead:hover ~ #content {
opacity: 0.1;
transition: all 0.5s linear 0.1s;
}
#content {
transition: all 0.5s linear 0.1s;
}
```

If this idea is too silly, feel free to close or delete the entry.

**Comment by Ver3** [comment]
If not implemented as a feature, it may have a place here:

https://wpastra.com/docs-category/custom-code-snippets/

**Comment by Nikschavan** [comment]
This has been added to Astra's documentation - https://wpastra.com/docs/dim-content-on-menu-hover/

Thank you for this @Ver3 :)

**Comment by Ver3** [comment]
Awesome!
