### ISSUE TITLE
Customizer font-size setting doesn't work properly on tablet and mobile

### ISSUE THREAD

**Issue by ramonztro** [brainstormforce/astra#487]
To reproduce the issue, you need to set different font-size for desktop, tablet and mobile, on the Astra customizer (Appearance>Customize>Typography>Base Typography).

What happens is that desktop font-size works fine, but tablet and mobile font-size are rendered smaller than what you set.

![01](https://user-images.githubusercontent.com/3981052/37522919-303047d2-2904-11e8-926e-c39068ebb9b8.jpg)
![02](https://user-images.githubusercontent.com/3981052/37522921-304fd35e-2904-11e8-811f-802e7ee058c4.jpg)
![03](https://user-images.githubusercontent.com/3981052/37522922-306d785a-2904-11e8-98c6-f4d0ee89f3cb.jpg)
![04](https://user-images.githubusercontent.com/3981052/37522923-308d37f8-2904-11e8-9bc0-ea71a0b67d1e.jpg)
![05](https://user-images.githubusercontent.com/3981052/37522924-30ae4cb8-2904-11e8-90d9-8cf30338ff93.jpg)
![06](https://user-images.githubusercontent.com/3981052/37522926-30d4f8f4-2904-11e8-924c-0f61f20b8f65.jpg)

**Comment by Nikschavan** [comment]
Thank you for the report @ramonztro The PR #490 fixes this problem.
The problem was because of incorrect `rem` calculations for the `<body>`.
