### ISSUE TITLE
Some Google fonts are not loaded properly

### ISSUE THREAD

**Issue by ramonztro** [brainstormforce/astra#488]
When you select "Slabo27px" and "Exo 2" fonts on customizer, it does not load or render the fonts. May be happening with other fonts as well, though I was just able to check these two.

**Comment by Nikschavan** [comment]
It seems that we are not adding the font category in the font family right now.
What Google recommends is `Slabo 27px', serif ` and Astra is just adding `Slabo 27px'` right now that is not displaying the font-family correctly.

**Comment by Nikschavan** [comment]
#491 fixed this and this was released in v1.2.7 of Astra theme.
