### ISSUE TITLE
HTML Block (Iframes) break out of container

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4922]
### Describe the bug:
I have added a google maps iframe to my post, but the content will break out of the boxed container. This issue was introduced some versions ago, I originally reported this via the pro version bugtracker, the support said the issue is forwarded, but like many other issues the information was not transmitted/bug was not fixed. Hopefully the github bugtracker receives more views.

### To reproduce:

1. Create a new website
2. Create a new blog post
3. Create a html block
4. paste the code below
5. publish page
6. view in mobile mode

html block code:
```
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2472.019073394816!2d8.74952321577762!3d51.714393579669675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47ba4cbd06aeb841%3A0xadeabc7348840e5b!2sCapitol%20Paderborn!5e0!3m2!1sde!2sde!4v1655287876319!5m2!1sde!2sde" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" width="600" height="450"></iframe>
```

### Screenshots:
Bug:
![image](https://user-images.githubusercontent.com/6888294/212413534-ebfcd528-00be-4232-82eb-d3620fa99a80.png)

With workaround
```css
embed,
iframe,
object {
 max-width:100% !important;
}
```
![image](https://user-images.githubusercontent.com/6888294/212413679-01860ef5-c4d7-4f13-8f39-b72265edaf41.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
8.1.1

### Astra Theme version:
6.0.1

**Comment by thebengalboy** [comment]
This has been addressed and released with the version Astra theme 4.0.2. Thanks
