### ISSUE TITLE
Post Category Archive Page has a non-customizable border

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4923]
### Describe the bug:
There is this annoying border in the archive page. this appeared around 3.8.4 for no reason. within a later update the color changed (you can now configure global border colors), but it was never removed. why is it there, please remove this border.

![image](https://user-images.githubusercontent.com/6888294/212415054-1311b0f3-f99b-45a5-be16-8b217e7e42c9.png)

### To reproduce:
1. create a new website
2. Set the background to a dark color
3. check a ctageory archive page

### Expected behavior:
I dont need this border. why is it there? Where else are those borders used?

workaround:
```css
.ast-separate-container .ast-archive-description,
.ast-separate-container .ast-author-box {
 border-bottom: 0;
}
```

This border also seems to be used in the comment form (highlighted in yellow here):
![image](https://user-images.githubusercontent.com/6888294/212416352-f639498d-308a-4614-9caf-7c169284b61e.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Astra Theme version:
4.0.1

**Comment by nathanrodrigues2111** [comment]
The mentioned border is essential to differentiate between heading section and the post below, This is also used to different container types so this border will be kept as it is @NicoHood
