### ISSUE TITLE
Customizer font setting will only show full integer value, no floating values

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4925]
### Describe the bug:
Look at this setting: global->buttons->font->font size and try to set it to 1.25. It will work, but after clicking outside the box, the input field will show 1.
![image](https://user-images.githubusercontent.com/6888294/212418307-259e8e96-1282-4916-bab6-2aa4d9ed06ac.png)

### To reproduce:
As described above. It might happen on other setting as well.

### Expected behavior:
The box should show `1.25` not `1`

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Astra Theme version:
4.0.1

**Comment by thebengalboy** [comment]
This is not a bug; we do not accept fractional font size values.

**Comment by NicoHood** [comment]
But the button size was 1.25 before the update. And thatswhy I've set it to this value again, to not run into a regression. Also "not accepting" is wrong, the input field DOES accept the value, it just does not DISPLAY it correctly.
