### ISSUE TITLE
[Feature Request] Set image size of related posts

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4926]
### Is your feature request related to a problem? Please describe.
Look at this: the images are of different hight, that looks weird. We should rather be able to use a custom size. 

![image](https://user-images.githubusercontent.com/6888294/212418755-d73a0a16-64c2-4a36-bf0e-d45b00f32bad.png)

### Describe the solution you'd like
I would prefer a dropdown of the registered wordpress image sizes, as I have a special feature image size registered.

### Describe alternatives you've considered
No workaround

**Comment by thebengalboy** [comment]
Hi @NicoHood 

At this time, we are not contemplating the implementation of a new control for this. However, it may be worthwhile for you to utilize the same size featured images.

Thanks
