### ISSUE TITLE
Please Check for Class Exists in class-astra-admin-loader.php

### ISSUE THREAD

**Issue by mediagiant** [brainstormforce/astra#4956]
I love the new loader and react project for settings, but can you please wrap the class initialization in ASTRA_THEME_DIR . 'admin/class-astra-admin-loader.php' with the below?

  if (!class_exists('Astra_Admin_Loader')) 
{
// define class
}

That way we don't have to manually add the check to functions.php when we want to override the loader experience with something more customized, allowing Astra to continue to update despite 3rd party customizations to this experience.

**Comment by Sudhanshu-1508** [comment]
Hi @mediagiant , Thank you for your suggestion on our theme.

I am glad to inform you that your suggestion and contribution is valuable to us.

We implemented your suggestion here - [PR](https://github.com/brainstormforce/astra/pull/5636)

Again, thank you for your contribution. 

Regards, 
Sudhanshu & Astra development team.
