### ISSUE TITLE
Customizer Preview does not use Link colors for Headlines

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4962]
### Describe the bug:
The customizer does not show the link colors for headlines

### To reproduce:
1. Add a custom Link Color to a H2 Headline
2. Open the page (it works)
3. Open the customizer (the normal headline or link color will be shown)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [?] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Astra Theme version:
4.0.2

**Comment by yssambare12** [comment]
Hi @NicoHood 

Thank you for bringing up the issue regarding the Astra theme's customizer not displaying link colors for headlines. We have investigated the matter and found that this issue has been addressed and resolved in the latest release version of Astra already hence it's not reproducing right now - [Screencast](https://d.pr/v/SbdHKA)

If you are still facing the same then we recommend updating your Astra theme to the latest version to benefit from the fix. Once you have updated, you should be able to see the link colors for headlines correctly within the customizer.

If you need anything else we can help you with, please don’t hesitate to [open a new ticket](https://wpastra.com/support/open-a-ticket/).
