### ISSUE TITLE
[Regression] List alignment wrong on frontend

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4966]
This has been a regression for a while now. I have reported it in the private premium bug report, but my issues are always closed and the promised follow-up is still missing.

Look at this:
https://test.nicohood.de/?p=211

![grafik](https://user-images.githubusercontent.com/6888294/214622897-e2ce3051-b834-433e-b19f-3f00e807edf8.png)

Those bullet points should not go outside the area. I was told this gets fixed, as it is a confirmed bug.

WP 6.1.1 Astra 4.0.2

**Comment by thebengalboy** [comment]
Hi @NicoHood 

For this regression issue, our tests yielded no reproducible results. Is there anything we're overlooking? Ref- https://d.pr/v/TVszUZ

**Comment by NicoHood** [comment]
This looks like what I want. But why does it look different on my frontend?

https://test.nicohood.de/?p=342

I have enabled most opt-in filters, maybe I am missing anything?

```
// 3.7.4 https://wpastra.com/docs/gutenberg-ui-improvements-with-astra/
add_filter( 'astra_get_option_improve-gb-editor-ui', '__return_true' );

// 3.8.3 https://wpastra.com/docs/improved-block-editor-experience
add_filter( 'astra_get_option_customizer-default-layout-update', '__return_true' );
add_filter( 'astra_get_option_wp-blocks-v2-ui', '__return_true' );

// 3.9.0 https://wpastra.com/updates/astra-3-9/#comment-100167
// There is no documentation about this yet, but it removes not required padding for full width layouts
// https://github.com/brainstormforce/astra/blob/c5bea1fbdac03cd22f27c66eb204a4f1230bb138/inc/dynamic-css/container-layouts.php#L118
add_filter( 'astra_stretched_layout_with_spacing', '__return_false' );

// 3.9.4 https://wpastra.com/docs/improved-spectra-compatibility/
add_filter('astra_spectra_gutenberg_compat_css', '__return_true');
```

**Comment by NicoHood** [comment]
You can find login credentials to that site in the privat bugtracker id #307485 (the ticket is unrelated to this issue, but the login credentials are the same).

**Comment by thebengalboy** [comment]
Thank you @NicoHood ; Please continue the discussion with our support superhero. They'll of course solve the problem you are experiencing. As this is not a core theme issue, I'm closing this issue here. Thanks
