### ISSUE TITLE
Post Top-Padding not working at all

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4967]
This is a regression from this bug:
https://github.com/brainstormforce/astra/issues/4450#issuecomment-1382342801

More details in the comment above, but just to replicate, here is the screenshot:
![image](https://user-images.githubusercontent.com/6888294/212411116-3a1a3f45-aec4-4fb6-ba6b-301fd0a4b44f.png)

WP 6.1.1 Astra 4.0.2

**Comment by thebengalboy** [comment]
@NicoHood For this regression issue, our tests yielded no reproducible results. Is there anything we're overlooking?

**Comment by NicoHood** [comment]
If you give me your email, I can send you the credentials of my test environment, where I am able to reproduce this.

**Comment by thebengalboy** [comment]
@NicoHood Please open a support [ticket here](https://wpastra.com/support/open-a-ticket/), our support team will help you out on this.

**Comment by NicoHood** [comment]
Sure. The ticket id is #307485 in the private astra bugtracker
