### ISSUE TITLE
List-Block text color not visible in Editor

### ISSUE THREAD

**Issue by NicoHood** [brainstormforce/astra#4972]
### Describe the bug:
With WordPress 6.1 the list block has changed and was divided into multiple blocks.

a) This broke the text color of existing blocks
b) The text color is not reflected in the gutenberg editor when editing

### To reproduce:
1. Create new post
2. Add a list element
3. Set the text color for that element (it will not show)

### WordPress version:
6.1.1

### Astra Theme version:
4.0.2

**Comment by yssambare12** [comment]
Hi @NicoHood 
We are not able to reproduce this issue,
Can you please provide more details regarding this?
Thanks!
