### ISSUE TITLE
Missing form fields on BuddyPress registration page with Astra >=4.1.0

### ISSUE THREAD

**Issue by AlceoMazza** [brainstormforce/astra#5079]
### Describe the bug:
Since version 4.1.0 of the theme, the form fields of the BuddyPress registration page are disappeared

### To reproduce:
1. Install and activate the BuddyPress plugin
2. Install and activate a version equal or higher to 4.1.0 of Astra theme
3. Go to the registration/sign-up page
4. See that the registration form and form fields are not printed out

### Expected behavior:
I expect to see the form fields in the BuddyPress sign-up page (as they were printed out up to the version 4.0.2 of the theme).

### Screenshots:
Astra version 4.0.2
![image](https://user-images.githubusercontent.com/57775045/228783832-a8decd84-927c-4f37-b2db-900f82bac8dc.png)

Astra version >=4.1.0
![image](https://user-images.githubusercontent.com/57775045/228783031-d62f1366-859f-47a1-a1e4-f49548a02e3a.png)

Twenty Twenty-Three 1.1
![image](https://user-images.githubusercontent.com/57775045/228784644-96099fd4-9b96-42f7-9046-0b3e5e97539c.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [x] This bug happens with the BuddyPress plugin activated alone
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2

### Astra Theme version:
\>= 4.1.0

**Comment by thebengalboy** [comment]
Hello @AlceoMazza 

The problem has been resolved, and an update has been released a few minutes ago. Kindly update to the latest version (4.1.3) and confirm if it addresses the issue.

**Comment by AlceoMazza** [comment]
Hi @thebengalboy
I've updated to Astra to 4.1.3 and the issue no longer occurs. Thanks for resolving.
