### ISSUE TITLE
Woocommerce '+' and '-' missing on single product pages after update

### ISSUE THREAD

**Issue by Estalhun** [brainstormforce/astra#5081]
### Describe the bug:
Woocommerce '+' and '-' missing on single product and cart pages after update.
Of course it happens when Astra Pro and Woocommerce is active.

### To reproduce:
1. Go to Customizer -> Woocommerce -> Misc -> Quantity Plus and Minus
2. Enable Quantity Plus and Minus
3. Check product page to see the expected behaviour:
4. Update from 4.0.2 to 4.1.2.
5. Clear all cache
6. Check product page again
7. Plus and minus signs are missing.
8. Be overwhelmed by the sight. :-)

### Expected behavior:
I want to see the expected + and -.

### Screenshots:
https://drive.google.com/drive/folders/1_QBuLWdoL_TB4xT2HwhhildkMOpDbKBP?usp=share_link

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2

### Astra Theme version:
4.1.2 and Astra pro 4.0.1 or 4.1.3

**Comment by lab4450** [comment]
https://www.facebook.com/groups/wpastra/posts/1559618394507419/?comment_id=1561180004351258

**Comment by thebengalboy** [comment]
Hello @Estalhun 

The problem has been resolved, and an update has been released a few minutes ago. Kindly update to the latest version (4.1.3) and confirm if it addresses the issue.

**Comment by Estalhun** [comment]
The problem was resolved with the update.
