### ISSUE TITLE
cart always empty

### ISSUE THREAD

**Issue by lab4450** [brainstormforce/astra#5083]
### Describe the bug:
slider in cart and quick add to cart are always empty. even so the cart has items.

### To reproduce:
0. go to wp-admin customize. woocommerce. single product. add to cart button. set behaviour has slide in.
1. go to a single product page. click add to cart button.
2. slide in cart will show
3. cart has no content
4. cart icon is counting the total of items correctly
5. cart dedicated page is working correctly

### Expected behavior:
cart should have content

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2
### Astra Theme version:
4.1.2 and Astra pro latest version
elementor and elementor pro latest version

a lot of other people on facebook can also replicate this

**Comment by lab4450** [comment]
https://www.facebook.com/groups/wpastra/posts/1559618394507419/?comment_id=1561180004351258

**Comment by ptrkx747** [comment]
Same problem here.

**Comment by asleepfromday** [comment]
This is affecting numerous sites and costing lots to all woocommerce/astra clients.  Please please please get this fixed soon!

**Comment by thebengalboy** [comment]
Hello @lab4450 @ptrkx747 @asleepfromday 

We are currently aware of the issue and actively working towards finding a suitable solution. As soon as the issue is resolved, we will release an update promptly. We appreciate your patience and cooperation while we work on this matter.

**Comment by thebengalboy** [comment]
Hello @lab4450 @ptrkx747 @asleepfromday

The problem has been resolved, and an update has been released a few minutes ago. Kindly update to the latest version (4.1.3) and confirm if it addresses the issue.

**Comment by ptrkx747** [comment]
Thanks for fixing. Problem seems solved.
