### ISSUE TITLE
Font-weight not available for all fonts

### ISSUE THREAD

**Issue by ramonztro** [brainstormforce/astra#512]
I'm trying to use font-weight 900 for Lato (https://fonts.google.com/specimen/Lato), but it's not available through customizer.

**Comment by ramonztro** [comment]
Same for Poppins (https://fonts.google.com/specimen/Poppins)

**Comment by Nikschavan** [comment]
I have just submitted a PR #515 to fix this. This will be released in the next theme update.

Can you try the PR #515 and see if that is indeed fixing the error for you as well?

**Comment by ramonztro** [comment]
It's fixed!
