### ISSUE TITLE
PHP 8.2 Compatibility Issue - Site Crash

### ISSUE THREAD

**Issue by warpcoil** [brainstormforce/astra#5146]
After upgrading a WordPress Site from PHP7.4 to PHP8.2, site crashes.

This is a known issue whereby a previous warning is now an error from PHP8 onwards.
![FatalError](https://github.com/brainstormforce/astra/assets/5113027/5a96aad7-6cfb-4aff-9187-7a9d5abd9cb3)

Thank You and Kind Regards

Bobby

**Comment by neerajmasai** [comment]
Hey there @warpcoil,

Thank you for bringing this to our attention. I would like to inform you that we are currently in the process of ensuring compatibility with PHP 8+ for Astra.

Regarding your specific case, could you please provide me with the following details to help me reproduce the issue:

- The exported Customizer settings
- The current version of Astra that is active on your site.

Thank you for your cooperation.

Best regards,
Neeraj

**Comment by neerajmasai** [comment]
Hi @warpcoil 

Need few more details:

- Did the fatal error show up when upgrading from a previous version to the latest one?
- If yes, what was the earlier version of Astra and Astra Pro?
- Does downgrading the PHP Version to 7.4 solve the issue for you?

Best regards,
Neeraj

**Comment by warpcoil** [comment]
Hi @neerajmasai 

- No. The error occurred when upgrading the site to PHP8.2 from 7.4 (as we're trying to move from old EOL stuff).
- N/A
- That current live site is using 7.4 but we really need 7.4 gone due to EOL.

Thank You and Kind Regards

Bobby

**Comment by yssambare12** [comment]
Hi @warpcoil ,

I hope this message finds you well. I wanted to provide you with an update regarding the issue you reported after upgrading your WordPress site from PHP 7.4 to PHP 8.2.

I'm pleased to inform you that we have identified and resolved the problem. This fix will be included in our upcoming future release. [PR of this fix. ](https://github.com/brainstormforce/astra/pull/5180)

We apologize for any inconvenience this may have caused you and appreciate your patience while we worked on finding a solution. We understand the importance of a smoothly running website, and we are committed to providing you with the best possible experience.

If you need anything else we can help you with, please don’t hesitate to [[open a new ticket](https://wpastra.com/support/open-a-ticket/)]

**Comment by warpcoil** [comment]
Hi @yssambare12 

That is fantastic news, I look forward to when that's out so we can get rid of old infrastructure.

Have a lovely day.

Bobby
