### ISSUE TITLE
Can't set "Sticky: Desktop + Mobile" on header custom layout

### ISSUE THREAD

**Issue by ramonztro** [brainstormforce/astra#520]
When I create a header custom layout and select "Sticky: Desktop + Mobile" it changes back to "Sticky: Desktop" on save. 

***OBS:** I found a workaround for now, that is to select "Footer" instead of "Header", set "Sticky: Desktop + Mobile", save, change back to "Header" and update.*

Video: https://www.dropbox.com/s/di3aezlv7er2koz/header.mov?dl=0

**Comment by Nikschavan** [comment]
Thank you for the report @ramonztro. I have added this to Astra Pro's issue tracker. We will get this fixed until the next update of the addon.

**Comment by Nikschavan** [comment]
This is now fixed in Astra Pro.
