### ISSUE TITLE
Dynamic secondary menu depending on primary menu or page

### ISSUE THREAD

**Issue by st3phan76** [brainstormforce/astra#5276]
### Is your feature request related to a problem? Please describe.
I'd like to display the secondary menu depending on the primary menu or per page (display rules).

### Describe the solution you'd like
Using Astra Pro 'Pages Headers' I expected to set up this in Tab 'Site Header', like it is done with the primary menu in section 'Primary Header'. The section  'Below Header' does not provide an option like this.

### Describe alternatives you've considered
I changed both menus.
I use the primary menu as the secondary, because I can set it up in 'Site Header' depending on page to show/a display rule. I added it to the section 'below header' in the header-builder. The secondary menu is used as primary menu and is located in the section 'primary header'. A bit confusing, but it works ;-)

### Additional context/screenshots/videos
![grafik](https://github.com/brainstormforce/astra/assets/1858406/2847deab-7428-428b-9a1c-be7ec5f90f60)

**Comment by yssambare12** [comment]
Dear @st3phan76,

Thank you for reaching out to us and sharing your feature request with regards to displaying the secondary menu depending on the primary menu or per page (display rules) in Astra Pro. We appreciate your input and value your feedback in helping us improve our product.

As you rightly mentioned, implementing new features requires thorough research and careful consideration to ensure it aligns with our vision and the overall user experience. We have taken note of your request, and while we cannot guarantee immediate implementation, we will certainly evaluate its feasibility and relevance for future updates.

Your suggested solution of incorporating this feature into the 'Site Header' tab within 'Pages Headers' makes sense, and we will explore how we can enhance the header builder to accommodate this functionality seamlessly.

In the meantime, we understand that you have found a workaround by utilizing the primary menu as the secondary and vice versa. It's great to hear that this approach is working for you.

If you encounter any specific issues or need assistance with the existing features, please don't hesitate to contact us through the [support ticket system](https://wpastra.com/support/open-a-ticket/). Our support team is dedicated to providing timely and effective resolutions to all inquiries.

Once again, we thank you for taking the time to share your thoughts with us. User feedback is invaluable to us as it helps us prioritize our development efforts and deliver an even better product.

If you have any more ideas or suggestions in the future, please feel free to share them with us. We're always open to hearing from our users and making Astra Pro even more powerful and user-friendly.

Best regards.
