### ISSUE TITLE
The eye icon that toggles visibility of title not showing in block editor in v4.1.8 with Spectra

### ISSUE THREAD

**Issue by dushr** [brainstormforce/astra#5316]
### Describe the bug:
The Eye icon that toggles the visibility of title not showing up in the block editor is not showing. It was showing in v4.1.7. 
I noticed in the changelog of v4.1.8 there is a fix "Fix: Title enable/disable option missing in block editor with WordPress-6.3."

However, the fix doesn't work if you have Spectra plugin enabled

### To reproduce:
0. Ensure that spectra plugin is enabled
1. Edit an already existing **page** in block editor
2. Click on the title block
3. The eye icon is not shown

### Expected behavior:

On clicking the title of the page, there should be an eye icon visible that toggles the visibility of the title.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated **This bug happens with spectra activated**
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
v6.3
### Astra Theme version:
v4.1.8
### Spectra version
v2.7.4

**Comment by imnavanath** [comment]
Hi @dushr,

Thanks for contacting us.

We have fixed this issue and it is part of the upcoming release _(ETA is within 1-2 days)_.

For now here is the development version with the fix - https://share.getcloudapp.com/Z4uGBgx4 
You can use it on your site and verify the result.

It would be great if you verifiy and give us confirmation.

Best regards,
Astra Team
