### ISSUE TITLE
Bug: dots before menu items in Astra 4.3.0

### ISSUE THREAD

**Issue by StachRedeker** [brainstormforce/astra#5367]
### Describe the bug:
In Astra 4.3.0, the menu widgets in the website footer suddenly include dots before each menu item. It is not possible to remove the dots or give them a different colour.

### To reproduce:
Include a menu widget using the Astra footer builder. In Astra 4.3.0, there will be dots before the menu items. In Astra 4.2.1 and lower, there will not be.

### Expected behavior:
I expect there not to be any dots before the menu items, since this would make the versions backwards compatible.
If it was an added (hidden) feature, there should be a possibility to turn the dots off.

### Screenshots:
![expected behaviour](https://github.com/brainstormforce/astra/assets/64889011/3a409d92-5cca-471a-aefc-212ddcffa464)
Image: behaviour in Astra 4.2.1 and lower.

![new behaviour](https://github.com/brainstormforce/astra/assets/64889011/b4f1d670-91ee-4895-81f3-b38a5e5e41f8)
Image: behaviour in Astra 4.3.0.

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [] This bug happens with a default WordPress theme active --> This bug is relevant to the Astra theme itself.
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress latest

### Astra Theme version:
4.3.0

**Comment by yssambare12** [comment]
Hi @StachRedeker ,

Thank you for bringing the issue regarding the unexpected appearance of dots before menu items in Astra 4.3.0 to our attention. We understand the inconvenience this may have caused and sincerely apologize for any disruption it may have caused to your website.

We are actively working on resolving this issue, and we are committed to providing a solution in our upcoming hotfix release, scheduled for this Monday. Rest assured, once the update is available, you will be able to enjoy a seamless experience with Astra, just as you did in previous versions.

In the meantime, we truly appreciate your patience. If you're seeking an immediate solution, you can find temporary fixes in this [thread](https://wordpress.org/support/topic/bullets-appear-in-the-footer-menu/). These workarounds can be employed until the next update is released.

Please feel free to reach out if you have any further questions or require assistance with implementing the temporary solution. We are here to support you throughout this process.

Once again, we apologize for any inconvenience this issue has caused, and we are committed to delivering a fix as soon as possible.

Thank you for your understanding and continued support.

Best regards,
