### ISSUE TITLE
Desktop menu is quickly displayed during mobile browsing

### ISSUE THREAD

**Issue by brynner** [brainstormforce/astra#5399]
### Describe the bug:
I should only see the mobile menu when browsing on Mobile. But, the desktop version of the menu appears quickly.

### Expected behavior:
I should only see the mobile menu when browsing on Mobile

### Screenshots:
[Video available](https://github.com/brainstormforce/astra/assets/757276/24869ee2-b792-49b0-a46a-45824076829d)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.3.1

### Astra Theme version:
4.3.1

**Comment by brynner** [comment]
Bug fix:
`@media screen and (max-width: 921px) {
	#ast-desktop-header {
		display: none;
	}
}`

**Comment by imnavanath** [comment]
@brynner Above attached PR will fix the issue & we will line up it for the next-release.
