### ISSUE TITLE
Make whitelable Theme Image URL Relative

### ISSUE THREAD

**Issue by gravnetic** [brainstormforce/astra#543]
It would be nice to make the theme white label URL relative or add the default site URL to the custom meta box so that it automatically gets added to the image path.

**Comment by gravnetic** [comment]
The issue arises for me when cloning a site, not hotlinking from a single cross-domain instance.  I think the likelihood of a theme image gets hotlinked is very low.

**Comment by Nikschavan** [comment]
We have plans to make it possible to override the white label settings from the `wp-config.php` as well as a constant so that these settings will not be changed on site migration.

**Comment by gravnetic** [comment]
Nikschavan I am looking forward to this update!
