### ISSUE TITLE
W3 Validator errors for some customisations

### ISSUE THREAD

**Issue by ramonztro** [brainstormforce/astra#545]
When I run my site on https://validator.w3.org/ I get some CSS errors as shown below:

![01](https://user-images.githubusercontent.com/3981052/39185945-4e6b1fa6-479f-11e8-9156-eb24f35cac8e.png)
![02](https://user-images.githubusercontent.com/3981052/39185949-5196b226-479f-11e8-9d6a-2ba462b38893.png)
![03](https://user-images.githubusercontent.com/3981052/39185950-51c0b382-479f-11e8-857b-2c7bade7d4ff.png)
![04](https://user-images.githubusercontent.com/3981052/39185951-51e12fd6-479f-11e8-8cec-754dae11ecd5.png)

**Comment by Nikschavan** [comment]
Fixed with #565 
We will also be looking at similar fixes from Astra Pro
