### ISSUE TITLE
Parameter value wrong

### ISSUE THREAD

**Issue by IngoWinter** [brainstormforce/astra#5496]
### Describe the bug:
In [/inc/compatibility/class-astra-gutenberg.php on line 189](https://github.com/brainstormforce/astra/blob/v4.4.0/inc/compatibility/class-astra-gutenberg.php#L189) the first parameter for the `responsive_oembed_wrapper` method should be `$matches[1]` but it is `''`. That renders the `astra_responsive_oembed_wrapper_enable` Filter in [/inc/class-astra-after-setup-theme.php](https://github.com/brainstormforce/astra/blob/v4.4.0/inc/class-astra-after-setup-theme.php#L247) useless.

**Comment by IngoWinter** [comment]
#5541

**Comment by IngoWinter** [comment]
Please fix this soon. This bug shredders websites using gutenberg yt blocks.

**Comment by imnavanath** [comment]
Hi @IngoWinter,

Thanks for your contribution in Astra.

We have considered this fix with updated code in [this PR](https://github.com/brainstormforce/astra/pull/5533 ).

This fix can be released in v4.5.1.

Regards,
Navanath & Astra Team
