### ISSUE TITLE
Please rebuild the admin/assets/build/dashboard-app.js file with the latest changes

### ISSUE THREAD

**Issue by DAnn2012** [brainstormforce/astra#5524]
### Describe the bug:
Hi @imnavanath 

Please rebuild the **admin/assets/build/dashboard-app.js** file with the latest changes made to the source code, because some translations (such as "_Activate Now_" and "_Upgrade Now_") are not displayed due to the absence of the text domain.

Thank you.

### Expected behavior:

See #5379 #5486 (which were merged during October 2023)

while the "**admin/assets/build/dashboard-app.js**" file was rebuilt on September 15, 2023.

### Screenshots:

![astra-dashboard-app](https://github.com/brainstormforce/astra/assets/1197819/3cf70881-3658-4226-9d47-823192ab1d51)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

6.4 (it_IT)

### Astra Theme version:

4.4.1

**Comment by imnavanath** [comment]
Hi @DAnn2012,

In the release cycle, it skipped, but it has been rebuilt now. 

PS: [this commit](https://github.com/brainstormforce/astra/commit/b4cf147478df6bf8ff1d2f2fd24a910e70a46003)

Thanks
