### ISSUE TITLE
Hiding Overflow on Site Content is not needed and has unpredictable consequences

### ISSUE THREAD

**Issue by actual-saurabh** [brainstormforce/astra#553]
https://github.com/brainstormforce/astra/blob/e7d7bca16d2db7d08e5f6843a6ff3fe8594b2354/sass/site/layout/_layout.scss#L13-L15

As per https://css-tricks.com/almanac/properties/o/overflow/#article-header-id-2 (strong emphasis added by me)

> This is particularly useful in use with dynamic content and the possibility of an overflow causing serious layout problems. However, bear in mind that **content that is hidden in this way is utterly inaccessible (short of viewing the source)**. So for example a user has their default font size set larger than you would expect, you may be pushing text outside of a box and hiding it completely from their view.

This can have unpredictable consequences, for example: https://github.com/gocodebox/lifterlms/pull/519

WP Astra homepage with `.site`'s overflow set to hidden:
![WP Astra homepage with .site's overflow set to hidden](https://user-images.githubusercontent.com/1739834/39711437-5f1c845e-523d-11e8-9cf4-93bb07938ed7.png)

Unset `overflow: hidden;`:
![Unset overflow: hidden;](https://user-images.githubusercontent.com/1739834/39711544-a36c19bc-523d-11e8-80d6-a9c1d6301762.png)

Unsetting this has no consequence on the layout:
![Unsetting this has no consequence on the layout](https://user-images.githubusercontent.com/1739834/39711599-c744f944-523d-11e8-9d1e-f4ce3c046745.png)

I have tested this with a couple other sites as well. Can send in a PR, if needed.

**Comment by Nikschavan** [comment]
Hello @actual-saurabh,

Firstly, Thank you very much for this Issue and the PR.

You are right, `overflow: hidden`does cause some unintended problems. Like we faced problems when adding compatibility for Divi.
I will check some earlier logs on to why this was added as this exists from the very early days of Astra.

**Comment by actual-saurabh** [comment]
The [blame](https://github.com/brainstormforce/astra/blame/e7d7bca16d2db7d08e5f6843a6ff3fe8594b2354/sass/site/layout/_layout.scss#L13) shows that this was added in https://github.com/brainstormforce/astra/commit/6584757203078d21dbed978e7105c1737418661c in early Nov 2017 by @sandeshjangam 

I guess they can weigh in if there's a specific reason that we're missing before you close this.

**Comment by Nikschavan** [comment]
It seems this CSS was added early on as a compatibility fox for animation effects for Visual Composer and it's addons. When the animations appear on page, it was adding horizontal scrolls to the screen.

I tested this once again and this no longer seems to be an issue anymore and this CSS can be removed.

Thank you very much for this PR @actual-saurabh 👍

**Comment by Nikschavan** [comment]
Hey @actual-saurabh you had a contributon in removing this CSS .
I just wanted to inform you that `overflow-x:hidden` needs to be added for another problem [here](https://github.com/brainstormforce/astra/pull/867/files#diff-0fe483b0f480d8f63d00faa850fbade7R26) for gutenberg compatibility. We did search multiple ways to overcome this although for now that seems the only solution at the moment.

Feel free to reply if you have any comments regarding this.

**Comment by actual-saurabh** [comment]
overflow-x is not a problem, overflow-y: hidden messes up everything! :)
