### ISSUE TITLE
Page Header Display Rule does not work for taxonomies that have multiple post types assigned.

### ISSUE THREAD

**Issue by hzesen1221** [brainstormforce/astra#574]
Hi Astra devs,

Recently I installed a popular plugin named Enhanced Media Library Pro and through it I made Attachment post type also assigned to the builtin Categories taxonomy, so that I could easily manage my uploaded files.

All of a sudden the 'All Categores Archive' option under Posts is gone from the Display Rule. After digging into the code a bit I found this piece of code in the `get_location_selections()` function in `class-astra-target-rules-fields.php`:

```
$args       = array(
	'public'      => true,
	'object_type' => array( $post_type->name ),
);
$taxonomies = get_taxonomies( $args, 'objects' );
unset( $taxonomies['post_format'] );
```

Apparently, it would only work for taxonomies that are assigned to ONLY ONE post type. My suggestion here would be to utilize the `get_object_taxonomies()` function for each post type. My hack is to replace the above code with:

```
$taxonomies = array();
$taxonomy_names = get_object_taxonomies( $post_type->name );
foreach ($taxonomy_names as $taxonomy_name) {
	if ($taxonomy_name == 'post_format') continue;
	$args       = array(
		'public'      => true,
		'name' => $taxonomy_name,
	);
	$single_taxonomy = get_taxonomies( $args, 'objects' );
	if ( isset( $single_taxonomy[$taxonomy_name]->name ) && isset( $single_taxonomy[$taxonomy_name]->label ) ) {
		$taxonomies[$taxonomy_name] = (object)[
			'name' => $single_taxonomy[$taxonomy_name]->name,
			'label' => $single_taxonomy[$taxonomy_name]->label,
		];
	}
}
```

This works, but might not be the best way to implement. If by any chance possible, could you somehow utilize my hack above and come out with a better implementation that supports taxonomies attached to multiple post types?

Thanks a lot!

**Comment by patilvikasj** [comment]
Thanks for reporting this issue. 
We have made necessary changes in Astra Pro addon so that it supports taxonomies attached to multiple post types. 
This change will be added to the upcoming release with version **1.4.0**
