### ISSUE TITLE
Archive pages generates pagespeed penalties.

### ISSUE THREAD

**Issue by ipokkel** [brainstormforce/astra#698]
#When creating blog archive pages the image being pulled for the post image is a full size image resulting in high pagespeed penalties. (See astra/inc/extras.php > function astra_get_post_thumbnail)

* see pull request #697

Can you add an option in customiser under Layout > Blog > Blog / Archive where the default image size (full, large, medium, thumbnail)for the post thumbnail can be selected via dropdown.

**Comment by Nikschavan** [comment]
You are right, As a default, we should be loading `large` size instead of `full`. 
When loading the large size it is also in control of user what dimensions of the image should be displayed from `WP-Admin -> Settings -> Media`

Fixed in #697
