### ISSUE TITLE
Serious SEO issue: H1 is printed twice (once by Astra and once By Elementor)

### ISSUE THREAD

**Issue by bendqh** [brainstormforce/astra#738]
The webpage name (`h1` by default) that I give in WordPress edit mode can be for example "About us".

The webpage name (`h1` by choosing in Elementor) that I give in Elementor edit mode can be for example "About us".

Now I have two `h1` tags and it can be very problematic for the Google SEO robot scanning the site.

doing in the css file `.entry-title {display: none}` doesn't solve the issue. Anything else to do?

How can I ensrue Astra won't print `h1` tags at all? Thanks.

**Comment by Nikschavan** [comment]
When using page builder's, by default Astra disables it's page titles (not just hide using CSS)

- You can also disable the title manually from per page basis from the page meta settings.
- There is also a filter [astra_the_post_title_enabled](https://github.com/brainstormforce/astra/blob/3a85e30679929d471505c09de1d5bae2218cebff/inc/core/common-functions.php#L698) which you can use to disable the title from all the pages/posts.

**Comment by bendqh** [comment]
Maybe this is a new feature? Because it's not the case in my site...

**Comment by Nikschavan** [comment]
This has been around since very early versions of Astra. In the page meta, you should have the option to disable page title - https://cl.ly/0n1x0t1C0v2J

This option is automatically selected when creating a new page using elementor.

Cna you check if this page is selected on your site?

**Comment by bendqh** [comment]
I didn't use these options --- I could achieve the same goal from changing
Elementor's webpage settings:

It's "page layout" I (default/Elementor-canvas/Elementor-full_width).

Going through each page either from Astra OR Elementor is very
depressing...

Is there no other way? :\\\

**Comment by bendqh** [comment]
I mean: Is there no automatic way in one go? Having this option in Astra
could improve UX by easing users who "woke up late" in this regard.

I tried to talk with the Elemnetor team but Raz Ohad told me there is no
plan for this now.

**Comment by Nikschavan** [comment]
- You can edit the posts using the [Astra Bulk Edit](https://wordpress.org/plugins/astra-bulk-edit/) plugin.
- Second option is like I mentioned in an earlier comment, you can use the filter to disable the titles. [astra_the_post_title_enabled](https://github.com/brainstormforce/astra/blob/3a85e30679929d471505c09de1d5bae2218cebff/inc/core/common-functions.php#L698)

**Comment by sujaypawar** [comment]
@bendqh — please check the Astra Bulk edit plugin. It is the solution what you need.

https://wordpress.org/plugins/astra-bulk-edit/
