### ISSUE TITLE
Can't prevent Astra links from being hovered

### ISSUE THREAD

**Issue by bendqh** [brainstormforce/astra#744]
I've added either of the following in my main CSS file (via customize > customize-css):

```
a:hover, a focus {color: none !important}
a:hover, a focus {color: unset !important}
```

Either doesn't prevent the native Astra Gray hover color for links.

I don't want to have this Gray color for hovered/focused links --- I want the links to have their native color they have even when I hover on them.

I could solve this by doing something like:

`.menu a:hover, .menu a:focus {color: SAME_AS_ORIGINAL}
`

But this results in extra code I could avoid.

I believe there is some JavaScript clash here; please help --- if it's out of the scope, I'll ask someplace else, but I get the feeling it's quite unique to Astra JS as I don't recall such problem when generally working with CSS.

**Comment by Nikschavan** [comment]
Can you open up a [support ticket from the form](https://wpastra.com/support/submit-a-ticket/) so that this can check your case closely?

**Comment by bendqh** [comment]
Yes, but I prefer not to do it in this frame. I just wanted a hint so me and other Astra users could enjoy a hint or a solution. This seems to me to be Astra-JS based and I don't know where it might come from in Astra and I don't have the spare time to research sadly, so I just wanted a hint. If there isn't any, never mind for me; exceptionally, the workaround is good enough for me at the moment.
