### ISSUE TITLE
Missing escaping issues in following

### ISSUE THREAD

**Issue by sakinshrestha** [brainstormforce/astra#756]
* Use `esc_attr()` in the following:
    * inc\blog\blog-config.php line 166 and 428 implode( ' ', $read_more_classes )
    * inc\core\common-functions.php lines 985 and 987 implode( ',', $rgb )
* Use `esc_attr()` instead of `esc_html()`
    * esc_attr should be used to escape html attributes rather than esc_html
    * inc\compatibility\woocommerce\class-astra-woocommerce.php line 936 esc_html( implode( ' ', $cart_menu_classes ) )

**Comment by Nikschavan** [comment]
Closing this as it's fixed in #892
