### ISSUE TITLE
Images and Screenshot images license issue

### ISSUE THREAD

**Issue by sakinshrestha** [brainstormforce/astra#762]
* Readme screenshot images link and actual images used in screenshot are different
    * Provide proper links for images
* In assets\images\astra-starter-sites.jpg, you need to add links/licenses of the images used in this image as well as it is bundled with the theme

**Comment by Nikschavan** [comment]
We have added one missing image from the screenshot in the license declaration. (#825)

About the image [astra-starter-sites.jpg](https://github.com/brainstormforce/astra/blob/next-update-beta/assets/images/astra-starter-sites.jpg) This is a custom collage image made of screenshots of ready-made sites built using Astra. 

For this do we need to include license of all the individual images?
