### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by sakinshrestha** [brainstormforce/astra#764]
* The theme does not show tags for posts anywhere
* Is it only available for pro version?

**Comment by Nikschavan** [comment]
Tags can be turned on/off from the customizer settings.
You will need to go to Customizer -> Layout -> Blog -> Archive/Single Post

![image](https://user-images.githubusercontent.com/2931091/44525832-d8dc7d00-a6ff-11e8-867c-ff870b8be2f8.png)

Here the tags (and other metadata of a post) can be disabled/enabled and sorted.

**Comment by Nikschavan** [comment]
Tags can be enabled or disabled from the free theme as well as shown in the screenshot.
