### ISSUE TITLE
UI/UX: Primary Button

### ISSUE THREAD

**Issue by justintadlock** [brainstormforce/astra#772]
In the customizer, the theme is using the primary button color for an external link.  At the very least, change that to the secondary button color or use a plain link.  In WP, the primary button has very specific actions associated with it.  It makes for a poor user experience when the primary button does something completely different.

![primary-button](https://user-images.githubusercontent.com/1816309/44554071-2e5f5c80-a6f5-11e8-9cdf-bf10d6d3da0b.png)

**Comment by shubhw12** [comment]
@justintadlock  Thank you for your valuable inputs. We have fixed this in #1614.
