### ISSUE TITLE
Tag mismatch - opening tag is H6, closing tag is H5

### ISSUE THREAD

**Issue by pixelbrad** [brainstormforce/astra#804]
Somehow my IDE caught this. I thought you guys should be aware too :)

https://github.com/brainstormforce/astra/blob/fb8903baf0c821c6f26de64fbc223babe63fcaf5/inc/compatibility/lifterlms/class-astra-lifterlms.php#L243

**Comment by Nikschavan** [comment]
Thank you for the report @pixelbrad.
We have fixed this in the upcoming beta version of the theme.
