### ISSUE TITLE
[Feature Request] Ability to enable comments on pages

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#869]
Hello!

My subscribers are often asks how to enable comments on pages in Astra theme. It may be needed for info businessman who places theirs tripwire on separate pages made with any page builder.
People write comments and another people see that here are somebody alive and also can write their questions or comments too.

Thanks!

**Comment by Nikschavan** [comment]
Comments can be enabled on pages from per page bases.
1. Enable `Discussion` from screen options
![image](https://user-images.githubusercontent.com/2931091/46330961-477ff500-c633-11e8-9719-16992ab59bb4.png)

2. Select `Allow Comments` from the Discussion metabox
![image](https://user-images.githubusercontent.com/2931091/46330982-62526980-c633-11e8-8847-d63c629135f6.png)

**Comment by parfilov** [comment]
I completely forgot about it. Thank you!
