### ISSUE TITLE
[LifterLMS Compatibility] Missing Icon for Memberships tab on Dashboard

### ISSUE THREAD

**Issue by actual-saurabh** [brainstormforce/astra#871]
I introduced a "My Memberships" section in LifterLMS recently after which some users pointed out that it didn't have an icon on their sites using Astra:

![screen shot 2018-10-02 at 9 13 50 am](https://user-images.githubusercontent.com/1739834/46328247-e3096980-c623-11e8-96a7-ac26cc39c936.png)

IMO, the ["users" icon](https://fontawesome.com/icons/users?style=solid) is the only icon in fa that makes sense:

![screen shot 2018-10-02 at 9 12 42 am](https://user-images.githubusercontent.com/1739834/46328279-059b8280-c624-11e8-8528-b75d795746c2.png)

**Comment by Nikschavan** [comment]
Thank you for this fix @actual-saurabh.
While you are at this, you might also want to have a look at #874 :)

**Comment by Nikschavan** [comment]
Fixed in #873 

This will be merged to master in the upcoming release.
