### ISSUE TITLE
LifterLMS: Add icon for the 'My Grades' link in Student Dashboard

### ISSUE THREAD

**Issue by Nikschavan** [brainstormforce/astra#874]
![image](https://user-images.githubusercontent.com/2931091/46329176-6e392e00-c629-11e8-8caf-281c8b02805b.png)

I think icons [welcome-learn-more](https://developer.wordpress.org/resource/dashicons/#welcome-learn-more) or [awards](https://developer.wordpress.org/resource/dashicons/#awards) can fit here.

The icons can be selected from the [dashicons icon library](https://developer.wordpress.org/resource/dashicons/).

Similar to #871

**Comment by actual-saurabh** [comment]
@Nikschavan or, instead of mixing icon packs, I could use [graduation-cap](https://fontawesome.com/icons/graduation-cap?style=solid) which is similar to [welcome-learn-more](https://developer.wordpress.org/resource/dashicons/#welcome-learn-more). What do you think?

**Comment by Nikschavan** [comment]
Thank you for the PR @actual-saurabh :)

Fixed in #875
