### ISSUE TITLE
[FR] Icons in new (mega)menu system

### ISSUE THREAD

**Issue by Ver3** [brainstormforce/astra#921]
Short: IF builder is installed THEN use it's iconfont for menu.

So basically you can only use icons in menu's when you have Elmentor, Beaver or some other builder installed. I hope this mean Astra stays light but you still have options like this old plugin: https://nl.wordpress.org/plugins/menu-icons/

Worth thinking about?

**Comment by Nikschavan** [comment]
We have thought about adding fonts from the theme although never actually added it to keep the theme lightweight, as you mentioned.

We are experimenting with inline-SVG icons in another plugin for Astra.
This will not add HTTP requests to load font library and also will not load all the font library even if only a few icons are used on the page.
When that gets finalized we can revisit adding icon options for the menu.

Do let me know if you have any other suggestions regarding this.
