### ISSUE TITLE
[Suggestion] Remove redundant links for SEO improvement

### ISSUE THREAD

**Issue by parfilov** [brainstormforce/astra#923]
Hello! I want to suggest Astra logo and menu SEO improvement.

It's good for SEO when there is no links on the page to itself. So I want to suggest to: 

- remove logo link on front page;
- remove menu item link on active page.

There is a plugin https://wordpress.org/plugins/remove-redundant-links/ but it's 8 years without updates and causes errors with some WP configurations.

Hope you add this into Astra roadmap.

Regards,
Alex from WPlovers

**Comment by Nikschavan** [comment]
Thank you for the report @parfilov, 
Although, The logo in the theme is displayed using WordPress' native function [the_custom_logo()](https://developer.wordpress.org/reference/functions/the_custom_logo/) and this adds an image as well as the required link. 

Changing this default functionality should be done from a separate plugin or a snippet.
Right now this is not in our milestone to build this type of functionality for Astra.
