### ISSUE TITLE
Gutenberg Columns bad padding on mobile / stack

### ISSUE THREAD

**Issue by whatsnewsisyphus** [brainstormforce/astra#975]
![screenshot 2019-01-03 14 50 29](https://user-images.githubusercontent.com/454772/50658337-0adfd480-0f67-11e9-959e-9ed611bb31c9.png)
The addressing of columns by child order status causes them to be misaligned when columns stack in smaller media queries.

**Comment by whatsnewsisyphus** [comment]
I think astra could do better with spacing and column fitting of gutenberg more generally as well. I don't want to give names but a quick look at the other major themes of this sort might help to see what is missing.

**Comment by Nikschavan** [comment]
Columns should be fixed from the PR #980 

To improve this further, We will be looking into reviewing complete Gutenberg compatibility in the next update.

**Comment by whatsnewsisyphus** [comment]
Now they don't stack at all, it has three columns even on mobile.

**Comment by whatsnewsisyphus** [comment]
Fixed the stacking, but now they have a ridiculous margin in between them 10px+32px+32px+10px makes up a 82px valley between text. Why not use grid-column-gap / column-gap and embrace the css grid?

**Comment by premanshup** [comment]
1. The margin between the columns is added by Gutenberg which is 32px + 32 px. The 10px + 10px is a padding added by Astra.

2. We have removed the extra padding 10px + 10px in the PR #1090 which was added by Astra. Now there should be a gap of only 32px + 32px which is default added by Gutenberg itself.

3. Why not use grid-column-gap / column-gap and embrace the CSS grid? - Gutenberg uses flex-basis to display the Columns. In order to use Grid, we will have to override the CSS of flex and then make changes according to it which will increase CSS in Astra and will not be the best practice.

**Comment by whatsnewsisyphus** [comment]
Sorry about the grid suggestion, I have looked into more of the Gutenberg scafolding since and it didn't make sense. I have a more general suggestion though that would really add to Astra and keep designs consistent with changing elements.

Create a universal spacing unit setting that applies to all elements paddings and margins so that the user can set it to one value and everything is proportionally spaced. (use 2x universal spacing unit) when needed. The individual element spacing settings can then override individual elements out of the universal spacing proportions. This way you don't randomly have differing margins for the container, columns, headers and such. 

This is what I do with my child theme. For example, I have set my universal spacing to 15px. This applies 15px vertical and 30 px padding on the header, 30 and 45px top and bottom margins on the primary, 30px Gutenberg column gaps, 15px bottom margin on block elements and so forth. So with one setting change I can space out the site and everything remains proportional and even.

**Comment by premanshup** [comment]
Thank you for the suggestion but this will not be possible at the moment. As Gutenberg sets spacing on the blog level and theme provides options for global spacings like Content Padding/Margin, Header Padding/Margin, Footer Margin/Padding. 

Also, Managing all the Gutenberg blocks will be very complicated, we will have to check different column layouts like for 2 columns, 3 columns, 4 columns and so on. This will be considered as a different module for just managing the Gutenberg spacings. 

This will be very complicated to maintain too. As you can see in this issue only, we added 10px of padding it led to more issues. In the future, if WordPress changes the margin or padding, this will directly affect our settings and there will be chances that this may break your UI.

As of now, we might not be able to introduce this.

**Comment by whatsnewsisyphus** [comment]
I don't know why you say it's complicated when it's a few lines of code with media queries in sass to handle the spacing. This is what unifying/starter themes are supposed to do.

Gutenberg is built to be styled by theme designers, wordpress offers you the base styles with every update, even offers a sass framework with variables if you so wish to use that.

**Comment by Nikschavan** [comment]
The original issue was fixed in #1090.

About spacing - We can certainly try to unify the spacings, We do have plans to overhaul CSS and also incorporate suggestion in #788.

Changing the CSS will be a bit difficult in order to make the changes without breaking any designs on existing sites built by users.

**Comment by whatsnewsisyphus** [comment]
> The original issue was fixed in #1090.
> 
> About spacing - We can certainly try to unify the spacings, We do have plans to overhaul CSS and also incorporate suggestion in #788.
> 
> Changing the CSS will be a bit difficult in order to make the changes without breaking any designs on existing sites built by users.

Thanks. I understand that the change will be difficult and potentially break a few sites, but planning for the long term will break exponentially fewer sites and require fewer support requests down the line. I think Astra, now that it has established the momentum to be one of the go-to themes particularly for its speed, should look into the long term and carefully establish systems that can accommodate changes a few years into the future without excessive bloat.

While you still can, a push where you put out a bulletin for a couple weeks with changes and increased customer support for a month following an overhaul should be worth staying relevant a few years into the future as less well coded themes suffer bloat and Frankenstein like styling frameworks. Same goes for php autoloading and DRYer code.

I look forward to working with Astra(Pro user / child theme developer here) in the future.
