### ISSUE TITLE
[Feature Request] Navigation Drawer

### ISSUE THREAD

**Issue by ttstauss** [brainstormforce/astra#990]
I left this comment on a feature request over on the Elementor Repo, but I figured this could also be addressed by the Astra team:

> I'd like to add that having robust drawer options seems like a must-have nowadays.

> It's very common in web design best practices: [https://material.io/design/components/navigation-drawer.html](url)

> The ability to add multiple to a page would also allow for really great (and creative) design. As an example check out how Hims (https://www.forhims.com/) uses them on both the left side and right side by selecting either Shop/Learn or Cart/Login (view how it changes for desktop and mobile). It's beautifully done.

> Giving WordPress users a way to do this in [Astra] would be a great design choice.

**Comment by whatsnewsisyphus** [comment]
They have a flyout menu option in the Pro version.

**Comment by ttstauss** [comment]
@whatsnewsisyphus, I didn't know that. Could you point me to the documentation for it? I can't seem to find it anywhere.

**Comment by whatsnewsisyphus** [comment]
[Mobile Header with astra](https://wpastra.com/docs/mobile-header-with-astra/)

**Comment by ttstauss** [comment]
@whatsnewsisyphus, thanks!

I can see how this somewhat addresses the request, however, it still leaves a lot to be desired. The fact that it is so tightly coupled with the mobile header menu options makes it unflexible (though it's still a really great option if you all you need is a flyout for your mobile menu). As an example, how would I add a second drawer like the example I gave? How about adding a drawer not tied to a menu at all (let alone the mobile menu)?

With the Elementor's update today, I wonder if this could be accomplished with their new popup features.

**Comment by whatsnewsisyphus** [comment]
I see, yeah I could see a drawer module with widget areas (that piggybacks on the css and js for the header to save size) could work.

**Comment by Nikschavan** [comment]
We plan to bring more header layouts from Astra Pro in a few upcoming updates. We do have the plan to bring this option from this new addon (Header Layouts).
